# Step 1. 전체 파일 통합 및 JOIN

## 0. 라이브러리 & 설정

In [39]:
import pandas as pd
import glob
import os

# ── 파일이 있는 폴더 경로 
DATA_DIR1 = "/Users/sj.kang/Desktop/project2/SKN30-2nd-1Team/data/raw/channels/csv"

print("DATA_DIR :", os.path.abspath(DATA_DIR1))

DATA_DIR : /Users/sj.kang/Desktop/project2/SKN30-2nd-1Team/data/raw/channels/csv

## 1. channels 파일 전체 통합

`channels_must_*.csv` 패턴으로 파일을 자동 탐색해서 하나로 합칩니다.

In [40]:
# 파일 목록 탐색
ch_files = sorted(glob.glob(os.path.join(DATA_DIR1, "channels_must_*.csv")))

print(f"발견된 channels 파일: {len(ch_files)}개")
for f in ch_files:
    print(f"  {os.path.basename(f)}")

발견된 channels 파일: 44개
  channels_must_6000_6049.csv
  channels_must_6050_6099.csv
  channels_must_6100_6149.csv
  channels_must_6150_6199.csv
  channels_must_6200_6249.csv
  channels_must_6250_6299.csv
  channels_must_6300_6349.csv
  channels_must_6350_6399.csv
  channels_must_6400_6449.csv
  channels_must_6450_6499.csv
  channels_must_6500_6549.csv
  channels_must_6550_6599.csv
  channels_must_6600_6649.csv
  channels_must_6650_6699.csv
  channels_must_6700_6749.csv
  channels_must_6750_6799.csv
  channels_must_6800_6849.csv
  channels_must_6850_6899.csv
  channels_must_6900_6949.csv
  channels_must_6950_6999.csv
  channels_must_7000_7049.csv
  channels_must_7050_7099.csv
  channels_must_7100_7149.csv
  channels_must_7150_7199.csv
  channels_must_7200_7249.csv
  channels_must_7250_7299.csv
  channels_must_7300_7349.csv
  channels_must_7350_7399.csv
  channels_must_7400_7449.csv
  channels_must_7450_7499.csv
  channels_must_7500_7549.csv
  channels_must_7550_7599.csv
  channels_must_7600_7649.csv
  channels_must_7650_7699.csv
  channels_must_7700_7749.csv
  channels_must_7750_7799.csv
  channels_must_7800_7849.csv
  channels_must_7850_7899.csv
  channels_must_7900_7949.csv
  channels_must_7950_7999.csv
  channels_must_8000_8049.csv
  channels_must_8050_8099.csv
  channels_must_8100_8149.csv
  channels_must_8150_8191.csv

In [41]:
# 파일별로 읽어서 리스트에 쌓기
ch_list = []
for f in ch_files:
    tmp = pd.read_csv(f)
    tmp["source_file"] = os.path.basename(f)   # 어느 파일에서 왔는지 추적용
    ch_list.append(tmp)
    print(f"  {os.path.basename(f):45s} {len(tmp):>4}행")

print()
all_channels = pd.concat(ch_list, ignore_index=True)
print(f"통합 후 shape : {all_channels.shape}")

  channels_must_6000_6049.csv                     50행
  channels_must_6050_6099.csv                     50행
  channels_must_6100_6149.csv                     50행
  channels_must_6150_6199.csv                     50행
  channels_must_6200_6249.csv                     48행
  channels_must_6250_6299.csv                     50행
  channels_must_6300_6349.csv                     49행
  channels_must_6350_6399.csv                     50행
  channels_must_6400_6449.csv                     50행
  channels_must_6450_6499.csv                     50행
  channels_must_6500_6549.csv                     50행
  channels_must_6550_6599.csv                     50행
  channels_must_6600_6649.csv                     50행
  channels_must_6650_6699.csv                     50행
  channels_must_6700_6749.csv                     50행
  channels_must_6750_6799.csv                     50행
  channels_must_6800_6849.csv                     49행
  channels_must_6850_6899.csv                     49행
  channels_must_6900_6949.csv                     49행
  channels_must_6950_6999.csv                     50행
  channels_must_7000_7049.csv                     50행
  channels_must_7050_7099.csv                     50행
  channels_must_7100_7149.csv                     49행
  channels_must_7150_7199.csv                     50행
  channels_must_7200_7249.csv                     50행
  channels_must_7250_7299.csv                     50행
  channels_must_7300_7349.csv                     50행
  channels_must_7350_7399.csv                     48행
  channels_must_7400_7449.csv                     50행
  channels_must_7450_7499.csv                     50행
  channels_must_7500_7549.csv                     50행
  channels_must_7550_7599.csv                     50행
  channels_must_7600_7649.csv                     49행
  channels_must_7650_7699.csv                     50행
  channels_must_7700_7749.csv                     50행
  channels_must_7750_7799.csv                     50행
  channels_must_7800_7849.csv                     49행
  channels_must_7850_7899.csv                     50행
  channels_must_7900_7949.csv                     50행
  channels_must_7950_7999.csv                     50행
  channels_must_8000_8049.csv                     50행
  channels_must_8050_8099.csv                     50행
  channels_must_8100_8149.csv                     50행
  channels_must_8150_8191.csv                     42행

통합 후 shape : (2181, 9)

In [21]:
# 중복 channel_id 확인
dup = all_channels.duplicated(subset="channel_id")
print(f"중복 channel_id : {dup.sum()}개")

if dup.sum() > 0:
    print("중복 행 제거")
    all_channels = all_channels.drop_duplicates(subset="channel_id").reset_index(drop=True)
    print(f"제거 후 shape  : {all_channels.shape}")

중복 channel_id : 0개

In [22]:
# null 현황
print("=== null 현황 ===")
print(all_channels.isnull().sum())
print()
all_channels.head(3)

=== null 현황 ===
channel_id            0
title                 0
published_at          0
country             220
uploads_playlist      0
subscriber_count      0
view_count            0
video_count           0
source_file           0
dtype: int64

,channel_id,title,published_at,country,uploads_playlist,subscriber_count,view_count,video_count,source_file
0,UCjb-oBKXwCu9pmObxwKe__Q,네오아카데미,2012-05-25T12:11:28Z,KR,UUjb-oBKXwCu9pmObxwKe__Q,417000,217873767,1500,channels_must_6000_6049.csv
1,UCltYvvwh_x2Ai4yRiMrbpjw,조두팔,2016-08-03T02:36:19Z,KR,UUltYvvwh_x2Ai4yRiMrbpjw,416000,307215141,360,channels_must_6000_6049.csv
2,UCrgjx6tf6T021T2i-k9cRIw,컴퍼니수수 Company Soosoo,2023-10-18T01:43:09.453776Z,NaN,UUrgjx6tf6T021T2i-k9cRIw,424000,44889303,30,channels_must_6000_6049.csv

In [23]:
# 저장
out_ch = os.path.join(DATA_DIR1, "all_channels.csv")
all_channels.to_csv(out_ch, index=False, encoding="utf-8-sig")
print(f"저장 완료 : {out_ch}")
print(f"shape     : {all_channels.shape}")

저장 완료 : /Users/sj.kang/Desktop/project2/SKN30-2nd-1Team/data/raw/channels/csv/all_channels.csv
shape     : (2181, 9)

In [9]:
df = pd.read_csv("/Users/sj.kang/Desktop/project2/SKN30-2nd-1Team/data/raw/channels/csv/all_channels.csv")
df

,channel_id,title,published_at,country,uploads_playlist,subscriber_count,view_count,video_count,source_file
0,UCjb-oBKXwCu9pmObxwKe__Q,네오아카데미,2012-05-25T12:11:28Z,KR,UUjb-oBKXwCu9pmObxwKe__Q,417000,217873767,1500,channels_must_6000_6049.csv
1,UCltYvvwh_x2Ai4yRiMrbpjw,조두팔,2016-08-03T02:36:19Z,KR,UUltYvvwh_x2Ai4yRiMrbpjw,416000,307215141,360,channels_must_6000_6049.csv
2,UCrgjx6tf6T021T2i-k9cRIw,컴퍼니수수 Company Soosoo,2023-10-18T01:43:09.453776Z,NaN,UUrgjx6tf6T021T2i-k9cRIw,424000,44889303,30,channels_must_6000_6049.csv
3,UCU31L3bxdzSFTu2PyfJteBA,KLAP ENTERTAINMENT,2020-09-08T10:18:54.720522Z,KR,UUU31L3bxdzSFTu2PyfJteBA,427000,161234073,1460,channels_must_6000_6049.csv
4,UCFT-PF577T6OfHobMu5MASw,전여옥TV,2018-07-13T04:28:16Z,KR,UUFT-PF577T6OfHobMu5MASw,426000,201521422,6560,channels_must_6000_6049.csv
...,...,...,...,...,...,...,...,...,...
2176,UCdrBnBNLsN4_cH32HWbr9qg,GH'S,2020-07-07T12:14:18.499582Z,KR,UUdrBnBNLsN4_cH32HWbr9qg,27600000,27795079226,1144,channels_must_8150_8191.csv
2177,UCiVs2pnGW5mLIc1jS2nxhjg,김프로KIMPRO,2017-11-11T17:13:52Z,KR,UUiVs2pnGW5mLIc1jS2nxhjg,132000000,141999459427,4120,channels_must_8150_8191.csv
2178,UClkRzsdvg7_RKVhwDwiDZOA,JFlaMusic,2011-08-22T11:36:50Z,KR,UUlkRzsdvg7_RKVhwDwiDZOA,17200000,4037343143,386,channels_must_8150_8191.csv
2179,UCaO6TYtlC8U5ttz62hTrZgg,JYP Entertainment,2008-01-25T07:45:44Z,NaN,UUaO6TYtlC8U5ttz62hTrZgg,31900000,27165369822,2779,channels_must_8150_8191.csv
2180,UCByBXiL8TC7atFvIuNC95Hg,DuDuPopTOY,2016-05-05T06:59:54Z,KR,UUByBXiL8TC7atFvIuNC95Hg,11300000,5300276340,2238,channels_must_8150_8191.csv

## 2. videos 파일 전체 통합

`videos_*.csv` 패턴으로 파일을 탐색합니다.  
각 파일에 **컬럼 밀림 오염 행**(published_at에 날짜 대신 숫자가 들어간 행)이  
포함되어 있을 수 있으므로 파일마다 필터링합니다.

In [24]:
DATA_DIR2 = "/Users/sj.kang/Desktop/project2/SKN30-2nd-1Team/data/raw/videos/csv"

In [25]:
vi_files = sorted(glob.glob(os.path.join(DATA_DIR2, "videos_*.csv")))

print(f"발견된 videos 파일: {len(vi_files)}개")
for f in vi_files:
    print(f"  {os.path.basename(f)}")

발견된 videos 파일: 44개
  videos_6000-6049.csv
  videos_6050-6099.csv
  videos_6100-6149.csv
  videos_6150-6199.csv
  videos_6200-6249.csv
  videos_6250-6299.csv
  videos_6300-6349.csv
  videos_6350-6399.csv
  videos_6400-6449.csv
  videos_6450-6499.csv
  videos_6500-6549.csv
  videos_6550-6599.csv
  videos_6600-6649.csv
  videos_6650-6699.csv
  videos_6700-6749.csv
  videos_6750-6799.csv
  videos_6800-6849.csv
  videos_6850-6899.csv
  videos_6900-6949.csv
  videos_6950-6999.csv
  videos_7000-7049.csv
  videos_7050-7099.csv
  videos_7100-7149.csv
  videos_7150-7199.csv
  videos_7200-7249.csv
  videos_7250-7299.csv
  videos_7300-7349.csv
  videos_7350-7399.csv
  videos_7400-7449.csv
  videos_7450-7499.csv
  videos_7500-7549.csv
  videos_7550-7599.csv
  videos_7600-7649.csv
  videos_7650-7699.csv
  videos_7700-7749.csv
  videos_7750-7799.csv
  videos_7800-7849.csv
  videos_7850-7899.csv
  videos_7900-7949.csv
  videos_7950-7999.csv
  videos_8000-8049.csv
  videos_8050-8099.csv
  videos_8100-8149.csv
  videos_8150-8191.csv

In [26]:
vi_list = []
total_bad = 0

for f in vi_files:
    tmp = pd.read_csv(f)

    # 오염 행 제거: published_at이 YYYY- 형식이 아닌 행
    bad_mask = ~tmp["published_at"].astype(str).str.match(r"\d{4}-", na=True)
    bad_count = bad_mask.sum()
    total_bad += bad_count

    tmp = tmp[~bad_mask].reset_index(drop=True)
    tmp["source_file"] = os.path.basename(f)
    vi_list.append(tmp)

    print(f"  {os.path.basename(f):40s} {len(tmp):>5}행  (오염 {bad_count}행 제거)")

print()
all_videos = pd.concat(vi_list, ignore_index=True)
print(f"통합 후 shape    : {all_videos.shape}")
print(f"총 오염 행 제거  : {total_bad}개")

  videos_6000-6049.csv                      2384행  (오염 20행 제거)
  videos_6050-6099.csv                      2460행  (오염 0행 제거)
  videos_6100-6149.csv                      2464행  (오염 0행 제거)
  videos_6150-6199.csv                      2500행  (오염 0행 제거)
  videos_6200-6249.csv                      2400행  (오염 0행 제거)
  videos_6250-6299.csv                      2412행  (오염 0행 제거)
  videos_6300-6349.csv                      2500행  (오염 0행 제거)
  videos_6350-6399.csv                      2500행  (오염 0행 제거)
  videos_6400-6449.csv                      2452행  (오염 0행 제거)
  videos_6450-6499.csv                      2480행  (오염 0행 제거)
  videos_6500-6549.csv                      2421행  (오염 0행 제거)
  videos_6550-6599.csv                      2425행  (오염 0행 제거)
  videos_6600-6649.csv                      2442행  (오염 0행 제거)
  videos_6650-6699.csv                      2425행  (오염 0행 제거)
  videos_6700-6749.csv                      2479행  (오염 0행 제거)
  videos_6750-6799.csv                      2500행  (오염 0행 제거)
  videos_6800-6849.csv                      2376행  (오염 0행 제거)
  videos_6850-6899.csv                      2376행  (오염 0행 제거)
  videos_6900-6949.csv                      2405행  (오염 0행 제거)
  videos_6950-6999.csv                      2485행  (오염 0행 제거)
  videos_7000-7049.csv                      2455행  (오염 0행 제거)
  videos_7050-7099.csv                      2500행  (오염 0행 제거)
  videos_7100-7149.csv                      2402행  (오염 0행 제거)
  videos_7150-7199.csv                      2424행  (오염 0행 제거)
  videos_7200-7249.csv                      2500행  (오염 0행 제거)
  videos_7250-7299.csv                      2468행  (오염 0행 제거)
  videos_7300-7349.csv                      2500행  (오염 0행 제거)
  videos_7350-7399.csv                      2389행  (오염 0행 제거)
  videos_7400-7449.csv                      2448행  (오염 0행 제거)
  videos_7450-7499.csv                      2500행  (오염 0행 제거)
  videos_7500-7549.csv                      2481행  (오염 0행 제거)
  videos_7550-7599.csv                      2451행  (오염 0행 제거)
  videos_7600-7649.csv                      2484행  (오염 0행 제거)
  videos_7650-7699.csv                      2466행  (오염 0행 제거)
  videos_7700-7749.csv                      2500행  (오염 0행 제거)
  videos_7750-7799.csv                      2465행  (오염 0행 제거)
  videos_7800-7849.csv                      2422행  (오염 0행 제거)
  videos_7850-7899.csv                      2436행  (오염 0행 제거)
  videos_7900-7949.csv                      2500행  (오염 0행 제거)
  videos_7950-7999.csv                      2475행  (오염 0행 제거)
  videos_8000-8049.csv                      2464행  (오염 0행 제거)
  videos_8050-8099.csv                      2454행  (오염 0행 제거)
  videos_8100-8149.csv                      2454행  (오염 0행 제거)
  videos_8150-8191.csv                      2052행  (오염 0행 제거)

통합 후 shape    : (107576, 12)
총 오염 행 제거  : 20개

In [27]:
# 타입 변환
all_videos["published_at"] = pd.to_datetime(all_videos["published_at"], utc=True, errors="coerce")
all_videos["is_shorts"]    = all_videos["is_shorts"].astype(str).str.lower() == "true"

# published_at / channel_id null 제거
before = len(all_videos)
all_videos = all_videos.dropna(subset=["channel_id", "published_at"]).reset_index(drop=True)
print(f"null 제거 : {before - len(all_videos)}행 → {len(all_videos):,}행 남음")

null 제거 : 0행 → 107,576행 남음

In [28]:
# 중복 video_id 확인
dup_vi = all_videos.duplicated(subset="video_id")
print(f"중복 video_id : {dup_vi.sum()}개")

if dup_vi.sum() > 0:
    all_videos = all_videos.drop_duplicates(subset="video_id").reset_index(drop=True)
    print(f"제거 후 shape : {all_videos.shape}")

중복 video_id : 150개
제거 후 shape : (107426, 12)

In [29]:
# null 현황
print("=== null 현황 ===")
print(all_videos.isnull().sum())
print()
all_videos.head(3)

=== null 현황 ===
idx                 0
channel_id          0
channel_title       0
video_id            0
video_title         0
published_at        0
duration_sec      266
is_shorts           0
view_count         12
like_count       2848
comment_count    2301
source_file         0
dtype: int64

,idx,channel_id,channel_title,video_id,video_title,published_at,duration_sec,is_shorts,view_count,like_count,comment_count,source_file
0,6000,UCltYvvwh_x2Ai4yRiMrbpjw,조두팔,XJ6aLskAyMQ,조두팔 엽떡먹방영상 모음집,2024-09-24 12:00:37+00:00,973.0,False,355773.0,NaN,161.0,videos_6000-6049.csv
1,6000,UCltYvvwh_x2Ai4yRiMrbpjw,조두팔,BYlYxENvkL0,둘째출산 2주전 조두팔 (+30kg),2024-10-15 09:47:21+00:00,294.0,False,525675.0,NaN,188.0,videos_6000-6049.csv
2,6000,UCltYvvwh_x2Ai4yRiMrbpjw,조두팔,m3FYBFwhvr8,둘째 출산하고왔어요,2024-10-31 11:49:31+00:00,288.0,False,391770.0,NaN,183.0,videos_6000-6049.csv

In [30]:
# 저장
out_vi = os.path.join(DATA_DIR2, "all_videos.csv")
all_videos.to_csv(out_vi, index=False, encoding="utf-8-sig")
print(f"저장 완료 : {out_vi}")
print(f"shape     : {all_videos.shape}")

저장 완료 : /Users/sj.kang/Desktop/project2/SKN30-2nd-1Team/data/raw/videos/csv/all_videos.csv
shape     : (107426, 12)

## 3. channel_id 기준 JOIN

`all_channels`와 `all_videos`를 `channel_id`로 조인합니다.  
영상 파일은 채널당 여러 행이 있으므로 조인 방식에 따라 결과가 달라집니다.

| 방식 | 설명 | 용도 |
|---|---|---|
| **wide (채널 단위)** | videos를 채널 단위로 집계 후 1:1 조인 | 머신러닝 (XGBoost 등) |
| **long (영상 단위)** | 채널 정보를 각 영상 행에 붙이는 1:N 조인 | 시계열 분석, LSTM |

아래는 두 방식 모두 제공합니다.

### 3-1. Wide 조인 (채널 단위, ML용)

In [31]:
# all_channels / all_videos 로드 (앞 단계에서 이어지는 경우 생략 가능)
all_channels = pd.read_csv(os.path.join(DATA_DIR1, "all_channels.csv"))
all_videos   = pd.read_csv(os.path.join(DATA_DIR2, "all_videos.csv"))
all_videos["published_at"] = pd.to_datetime(all_videos["published_at"], utc=True, errors="coerce")
all_videos["is_shorts"]    = all_videos["is_shorts"].astype(str).str.lower() == "true"

In [32]:
# videos → 채널 단위 집계
NOW = pd.Timestamp.now(tz="UTC")

def aggregate_videos(group):
    dates    = group["published_at"].sort_values(ascending=False).tolist()
    intervals = [(dates[i] - dates[i+1]).days for i in range(len(dates) - 1)]

    t3 = NOW - pd.Timedelta(days=90)
    t6 = NOW - pd.Timedelta(days=180)
    recent = sum(1 for d in dates if d >= t3)
    prev   = sum(1 for d in dates if t6 <= d < t3)

    shorts = group[group["is_shorts"] == True]
    normal = group[group["is_shorts"] == False]
    merged = group[["view_count","like_count","comment_count"]].dropna()

    return pd.Series({
        # 활동성
        "collected_video_count"     : len(dates),
        "days_since_last_upload"    : (NOW - dates[0]).days,
        "avg_upload_interval_days"  : round(float(__import__("numpy").mean(intervals)), 2)  if intervals else float("nan"),
        "std_upload_interval_days"  : round(float(__import__("numpy").std(intervals)), 2)   if intervals else float("nan"),
        "max_gap_days"              : max(intervals)                                         if intervals else float("nan"),
        "hiatus_count_30d"          : sum(1 for d in intervals if d >= 30),
        "upload_freq_change_rate"   : round((recent - prev) / (prev + 1e-9), 4),
        # 성과
        "avg_view_count"            : round(group["view_count"].mean(), 2),
        "std_view_count"            : round(group["view_count"].std(), 2),
        "avg_like_count"            : round(group["like_count"].mean(), 2),
        "avg_comment_count"         : round(group["comment_count"].mean(), 2),
        "avg_engagement_rate"       : round(
            ((merged["like_count"] + merged["comment_count"]) / (merged["view_count"] + 1e-9)).mean(), 6
        ) if not merged.empty else float("nan"),
        # Shorts
        "shorts_ratio"              : round(len(shorts) / (len(group) + 1e-9), 4),
        "avg_shorts_view"           : round(shorts["view_count"].mean(), 2) if not shorts.empty else float("nan"),
        "avg_normal_view"           : round(normal["view_count"].mean(), 2) if not normal.empty else float("nan"),
    })

video_agg = all_videos.groupby("channel_id").apply(aggregate_videos, include_groups=False).reset_index()
print(f"집계 후 shape : {video_agg.shape}")
video_agg.head(3)

집계 후 shape : (2180, 16)

,channel_id,collected_video_count,days_since_last_upload,avg_upload_interval_days,std_upload_interval_days,max_gap_days,hiatus_count_30d,upload_freq_change_rate,avg_view_count,std_view_count,avg_like_count,avg_comment_count,avg_engagement_rate,shorts_ratio,avg_shorts_view,avg_normal_view
0,UC-0C8yVGJy-cS4FGlYKelWw,50.0,2.0,0.12,0.33,1.0,0.0,5.000000e+10,37752.60,61939.97,477.26,91.78,0.015068,0.48,14386.92,59320.92
1,UC-3Fh1L6hOSV9ylvpr5g8_Q,50.0,1.0,1.10,0.79,3.0,0.0,5.000000e+10,2357385.06,2080005.03,30812.16,225.06,0.014922,0.12,1592607.33,2461672.93
2,UC-5acDjU6XFWu-__G17V_YQ,50.0,24.0,1.43,2.49,18.0,0.0,5.000000e-01,87151.62,89251.85,1608.84,75.90,0.020618,0.50,74925.20,99378.04

In [33]:
# video_count 컬럼명 충돌 방지
all_channels = all_channels.rename(columns={"video_count": "total_video_count"})

# inner join
df_wide = all_channels.merge(video_agg, on="channel_id", how="inner")

# 불필요 컬럼 제거
df_wide = df_wide.drop(columns=["uploads_playlist"], errors="ignore")

print(f"조인 전 channels : {len(all_channels)}행")
print(f"조인 후 wide     : {len(df_wide)}행  ← 차이 있으면 영상 없는 채널 존재")
print(f"최종 shape       : {df_wide.shape}")
df_wide.head(3)

조인 전 channels : 2181행
조인 후 wide     : 2180행  ← 차이 있으면 영상 없는 채널 존재
최종 shape       : (2180, 23)

,channel_id,title,published_at,country,subscriber_count,view_count,total_video_count,source_file,collected_video_count,days_since_last_upload,...,hiatus_count_30d,upload_freq_change_rate,avg_view_count,std_view_count,avg_like_count,avg_comment_count,avg_engagement_rate,shorts_ratio,avg_shorts_view,avg_normal_view
0,UCjb-oBKXwCu9pmObxwKe__Q,네오아카데미,2012-05-25T12:11:28Z,KR,417000,217873767,1500,channels_must_6000_6049.csv,50.0,5.0,...,0.0,-0.3871,135991.08,174506.62,5099.94,64.94,0.043194,0.4000,280223.60,39836.07
1,UCltYvvwh_x2Ai4yRiMrbpjw,조두팔,2016-08-03T02:36:19Z,KR,416000,307215141,360,channels_must_6000_6049.csv,50.0,4.0,...,2.0,-0.5000,409137.34,274502.71,2436.29,197.66,0.008128,0.1800,432547.22,403998.59
2,UCrgjx6tf6T021T2i-k9cRIw,컴퍼니수수 Company Soosoo,2023-10-18T01:43:09.453776Z,NaN,424000,44889303,30,channels_must_6000_6049.csv,30.0,227.0,...,4.0,0.0000,1496626.33,4034231.59,60187.10,5903.43,0.122282,0.2667,182216.62,1974593.50

In [34]:
# null 확인
null_w = df_wide.isnull().sum()
print("=== null 현황 ===")
print(null_w[null_w > 0] if null_w[null_w > 0].any() else "없음")

=== null 현황 ===
country                     219
avg_upload_interval_days      1
std_upload_interval_days      1
max_gap_days                  1
std_view_count                1
avg_like_count               42
avg_comment_count            27
avg_engagement_rate          67
avg_shorts_view             304
avg_normal_view              36
dtype: int64

In [35]:
out_wide = os.path.join(DATA_DIR2, "dataset_wide.csv")
df_wide.to_csv(out_wide, index=False, encoding="utf-8-sig")
print(f"저장 완료 : {out_wide}")
print(f"shape     : {df_wide.shape}")

저장 완료 : /Users/sj.kang/Desktop/project2/SKN30-2nd-1Team/data/raw/videos/csv/dataset_wide.csv
shape     : (2180, 23)

### 3-2. Long 조인 (영상 단위, LSTM·시계열용)

각 영상 행에 채널 기본 정보(구독자 수, 생성일 등)를 붙입니다.

In [36]:
# channels에서 영상별로 붙일 컬럼만 선택
ch_meta = all_channels[[
    "channel_id", "title", "published_at", "country",
    "subscriber_count", "view_count", "total_video_count"
]].rename(columns={
    "published_at" : "channel_created_at",
    "view_count"   : "channel_total_views",
})

df_long = all_videos.merge(ch_meta, on="channel_id", how="left")

print(f"조인 후 long shape : {df_long.shape}")
print(f"채널 정보 없는 영상 : {df_long['title'].isnull().sum()}개")
df_long.head(3)

조인 후 long shape : (107426, 18)
채널 정보 없는 영상 : 0개

,idx,channel_id,channel_title,video_id,video_title,published_at,duration_sec,is_shorts,view_count,like_count,comment_count,source_file,title,channel_created_at,country,subscriber_count,channel_total_views,total_video_count
0,6000,UCltYvvwh_x2Ai4yRiMrbpjw,조두팔,XJ6aLskAyMQ,조두팔 엽떡먹방영상 모음집,2024-09-24 12:00:37+00:00,973.0,False,355773.0,NaN,161.0,videos_6000-6049.csv,조두팔,2016-08-03T02:36:19Z,KR,416000,307215141,360
1,6000,UCltYvvwh_x2Ai4yRiMrbpjw,조두팔,BYlYxENvkL0,둘째출산 2주전 조두팔 (+30kg),2024-10-15 09:47:21+00:00,294.0,False,525675.0,NaN,188.0,videos_6000-6049.csv,조두팔,2016-08-03T02:36:19Z,KR,416000,307215141,360
2,6000,UCltYvvwh_x2Ai4yRiMrbpjw,조두팔,m3FYBFwhvr8,둘째 출산하고왔어요,2024-10-31 11:49:31+00:00,288.0,False,391770.0,NaN,183.0,videos_6000-6049.csv,조두팔,2016-08-03T02:36:19Z,KR,416000,307215141,360

In [ ]:
out_long = os.path.join(DATA_DIR2, "dataset_long.csv")
df_long.to_csv(out_long, index=False, encoding="utf-8-sig")
print(f"저장 완료 : {out_long}")
print(f"shape     : {df_long.shape}")

## 최종 산출물 요약

| 파일 | 단위 | 용도 |
|---|---|---|
| `all_channels.csv` | 채널 1행 | 원본 통합본 |
| `all_videos.csv` | 영상 1행 | 원본 통합본 |
| `dataset_wide.csv` | 채널 1행 | ML 모델 (XGBoost, LightGBM 등) |
| `dataset_long.csv` | 영상 1행 | 시계열 모델 (LSTM, Transformer 등) |