# 01a. 채널 정보 수집 — `channels.list` API

**목적:** youtube_channels_cleaned.csv 의 head(5) 샘플 채널에 대해  
YouTube Data API v3 `channels.list` 로 받을 수 있는 **모든 필드**를 확인한다.

| 표시 | 의미 |
|------|------|
| ⭐ MUST | 이탈 예측 피처 또는 영상 수집에 필수 |
| ○ OPTIONAL | 있으면 좋지만 없어도 됨 |

**API Quota 비용:** `channels.list` 1회 = **1 unit** (50채널 배치 가능)

## 0. 설정

In [ ]:
import os
import json
import pandas as pd
from pathlib import Path
from dotenv import load_dotenv
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

load_dotenv()

API_KEY = os.getenv('YOUTUBE_API_KEY')
assert API_KEY, '.env 파일에 YOUTUBE_API_KEY 를 설정하세요'

youtube = build('youtube', 'v3', developerKey=API_KEY)

ROOT     = Path('../../')          # 프로젝트 루트
CSV_PATH = ROOT / 'data' / 'raw' / 'youtube_channels_cleaned.csv'
OUT_DIR  = ROOT / 'data' / 'raw' / 'channels'
JSON_DIR = OUT_DIR / 'json'        # 원시 API 응답 저장
CSV_DIR  = OUT_DIR / 'csv'         # MUST 필드 가공본
JSON_DIR.mkdir(parents=True, exist_ok=True)
CSV_DIR.mkdir(parents=True, exist_ok=True)

# ─────────────────────────────────────────────────────────────
# 처리할 youtube_channels_cleaned.csv 의 행 인덱스 범위 (둘 다 inclusive)
# 예: START_IDX=0, END_IDX=49 → 0번째 ~ 49번째 행 (총 50개 채널) 처리
# 다음 실행 때는 직전 실행이 출력한 안내 메시지의 인덱스부터 이어서 처리
START_IDX = 0
END_IDX   = 49
# START_IDX = 250
# END_IDX   = 399
# ─────────────────────────────────────────────────────────────

print('API 연결 완료')

# python notebooks/01_data_collection/run_channel_batch.py --start 2000 --end 3999

API 연결 완료

## 1. 처리 대상 채널 불러오기 (`START_IDX` ~ `END_IDX`)

In [146]:
df_all = pd.read_csv(CSV_PATH)
df = df_all.iloc[START_IDX:END_IDX + 1].copy()

print(f'전체 채널 수: {len(df_all):,}')
print(f'이번 실행 범위: {START_IDX} ~ {END_IDX} (총 {len(df)}개 채널)')
df[['channel_name', 'youtube_channel_id']].head(10)

전체 채널 수: 8,192
이번 실행 범위: 800 ~ 849 (총 50개 채널)

                     channel_name        youtube_channel_id
800  부산희야TV(Korean Ghost Tracker)  UCPvt1dbhi23-FTpGYZrmpLw
801                       기타치는다람띠  UCgXzwGNQLKQ4LA4XmWYWuvw
802                  낚튜브 _NotTube  UC7ddGHlf5sUc3w3yeMRqTLA
803                          스타토이  UCJ2jmRmeLWFtVQQPsut9v8w
804               방랑이고싶다 BangLang  UCS_GfKlHjjFwgIqGyZOwbtA
805                           じゃぴ  UCktQ-dRsgT6IYjKXqw7fTCQ
806                  Online Topik  UCG6jmnh5Qw2SZYIPsN2Azfw
807                         천재아시안  UCa98sUKOO-0ZoqmnOlY1i2g
808                 kpop playlist  UCKFY1KpeayRWa1QUzk-d0zQ
809                  BROKENPASTEL  UC66duPrHKb_TJge0IL8x_9g

In [147]:
channel_ids = df['youtube_channel_id'].tolist()
print('수집할 channel_id:')
for cid in channel_ids:
    print(' ', cid)

수집할 channel_id:
  UCPvt1dbhi23-FTpGYZrmpLw
  UCgXzwGNQLKQ4LA4XmWYWuvw
  UC7ddGHlf5sUc3w3yeMRqTLA
  UCJ2jmRmeLWFtVQQPsut9v8w
  UCS_GfKlHjjFwgIqGyZOwbtA
  UCktQ-dRsgT6IYjKXqw7fTCQ
  UCG6jmnh5Qw2SZYIPsN2Azfw
  UCa98sUKOO-0ZoqmnOlY1i2g
  UCKFY1KpeayRWa1QUzk-d0zQ
  UC66duPrHKb_TJge0IL8x_9g
  UC5p-SkOSlkZRiF6CRdIFJvw
  UCopSrNAWJnzm4ETOS4mXHnw
  UCx7ThnRlyrSSiNCLIZI0aqQ
  UCW53Pedlt62rx5zuTRZKUow
  UC-MAo6JvPw49wWJzTePGF5Q
  UCfxGrUvr10MjaCVKE_HVGgw
  UCKcwMdtuEELC4hn_fUlfVrA
  UC9mpnu1x96y7utLpnYyU6kw
  UChC6A-YfVfQ9jbqG5zb4gjw
  UCUEAfMdSYiXDfRVxdfqAQrg
  UCGqrzELBIpH6kfgJsNcZgeQ
  UC0CN1kbW3RuSz60bE9ELHcw
  UCPQ887rCYjOSSxN6nXqAojg
  UC-Id9P16Dnutun3wual1fcA
  UCc8RR9yJEKVvP31OWBqhIjg
  UCHHmDl_k97jLSOYbKEflr5Q
  UCGGhcGI2JzKmtpSUkqSm7HQ
  UCfVqqxdFMvN4f0-isg0_bbw
  UCS7_uGiAocfn0JGrJliGVrA
  UC7SSJS5huELNkaI6XhoNpNw
  UCFHt4Drs8lmyd-aUsBqM5uQ
  UC76R9DL1NjD7aLr_C3eueLA
  UCA7WtDf9bYuRW1BowR00e6g
  UCsnakEva6XIr8rf0P8R_vBQ
  UCCtKt-yPCrhLd6nlgJQc4RQ
  UC3QWksal35X_nSXE8jC59_A
  UCYhXoMjqKjfbh_bg57CyTIQ
  UCH7XQue96n6LH2EBwcp5_Xw
  UC9hWQRe4QrUivXN3VO2iuMA
  UCVkE4YghTzGO61KHRsmffag
  UCIb_O9AwrmaCXquQJ0TIVdw
  UCnss3Bsz1g9XpJBNM62vlWA
  UCHzxtmQhWwhFajAhtgfumKg
  UCzDLR2GTRqNsIFSnLacmdKg
  UCkmNa3uEggjZis2eYbaXXnA
  UC20IAd2RgxMkSNAbiRVMdGQ
  UC6oN6MLpxu2CbCCIsQET0iA
  UCz0mNYCcfvetgrS7h0H-WcQ
  UC8RUkja-IDFu10i5Rq3LX0A
  UCstHL8TQy5hjCSIxK370aow

## 2. `channels.list` — 받을 수 있는 모든 part 호출

| Part | 주요 내용 |
|------|-----------|
| `snippet` | 채널명·설명·개설일·국가·썸네일 |
| `contentDetails` | ⭐ uploads 플레이리스트 ID (영상 수집 필수) |
| `statistics` | ⭐ 구독자 수·총 조회수·총 영상 수 |
| `topicDetails` | 콘텐츠 카테고리 토픽 |
| `brandingSettings` | 채널 키워드·배너 |
| `status` | 공개 상태·성인 인증 여부 |

In [148]:
PARTS = 'snippet,contentDetails,statistics,topicDetails,brandingSettings,status'
BATCH_SIZE = 50   # channels.list API 한 번에 최대 50개 ID

QUOTA_REASONS = {'quotaExceeded', 'rateLimitExceeded', 'dailyLimitExceeded', 'userRateLimitExceeded'}

channel_ids_all = df['youtube_channel_id'].tolist()
all_items = []                       # 누적된 channels.list 응답 items
last_completed_idx = START_IDX - 1   # 마지막으로 성공한 df_all 기준 인덱스
api_error = None                     # quota 등 에러 메시지

for batch_start in range(0, len(channel_ids_all), BATCH_SIZE):
    batch_ids   = channel_ids_all[batch_start:batch_start + BATCH_SIZE]
    range_lo    = START_IDX + batch_start
    range_hi    = START_IDX + batch_start + len(batch_ids) - 1
    print(f'  batch {batch_start // BATCH_SIZE + 1}: df_all[{range_lo}..{range_hi}] ({len(batch_ids)}개)')
    try:
        resp = youtube.channels().list(
            part=PARTS,
            id=','.join(batch_ids),
            maxResults=BATCH_SIZE,
        ).execute()
        all_items.extend(resp.get('items', []))
        last_completed_idx = range_hi
    except HttpError as e:
        reason = e.error_details[0]['reason'] if e.error_details else f'HTTP {e.resp.status}'
        api_error = reason
        print(f'  ✗ API 에러: {reason} — 이 배치 이후 중단')
        if reason not in QUOTA_REASONS:
            print('  (quota 에러는 아니지만 안전을 위해 중단합니다)')
        break

response = {'items': all_items}   # 이후 셀에서 사용하는 변수와 호환
n_units  = (last_completed_idx - START_IDX + 1 + BATCH_SIZE - 1) // BATCH_SIZE if last_completed_idx >= START_IDX else 0

print(f'\n수집 결과 — 응답 {len(all_items)}개 / 사용 quota: 약 {n_units} unit')
print(f'성공한 마지막 인덱스: {last_completed_idx}')
if api_error:
    print(f'에러 발생: {api_error}')

  batch 1: df_all[800..849] (50개)

수집 결과 — 응답 49개 / 사용 quota: 약 1 unit
성공한 마지막 인덱스: 849

## 3. 전체 응답 구조 확인

In [149]:
# 첫 번째 채널의 전체 응답을 그대로 출력
sample = response['items'][0]
print(json.dumps(sample, indent=2, ensure_ascii=False))

{
  "kind": "youtube#channel",
  "etag": "sfC3_tEWOW8ucgPl17yiCuamm5s",
  "id": "UCfxGrUvr10MjaCVKE_HVGgw",
  "snippet": {
    "title": "해븐마니아",
    "description": "'해븐마니아'는 공연에 특화된 서비스와 마케팅을 전담하는 브랜드이자,\n당사의 공연을 사랑해 주시는 마니아분들들을 지칭합니다.\n\n해븐마니아 분들을 위한 다양한 공연 콘텐츠를 제공해 드리겠습니다 :)\n많은 관심과 사랑 부탁드립니다!\n",
    "customUrl": "@heavenmania",
    "publishedAt": "2015-01-22T07:45:37Z",
    "thumbnails": {
      "default": {
        "url": "https://yt3.ggpht.com/55KJ50QbibFs9uau5nBklKkYrSgbXq1YQr3mdszpDSQDh2DfJxnYMDnvkLZv5PKxNEp87rtjKg=s88-c-k-c0x00ffffff-no-rj",
        "width": 88,
        "height": 88
      },
      "medium": {
        "url": "https://yt3.ggpht.com/55KJ50QbibFs9uau5nBklKkYrSgbXq1YQr3mdszpDSQDh2DfJxnYMDnvkLZv5PKxNEp87rtjKg=s240-c-k-c0x00ffffff-no-rj",
        "width": 240,
        "height": 240
      },
      "high": {
        "url": "https://yt3.ggpht.com/55KJ50QbibFs9uau5nBklKkYrSgbXq1YQr3mdszpDSQDh2DfJxnYMDnvkLZv5PKxNEp87rtjKg=s800-c-k-c0x00ffffff-no-rj",
        "width": 800,
        "height": 800
      }
    },
    "localized": {
      "title": "해븐마니아",
      "description": "'해븐마니아'는 공연에 특화된 서비스와 마케팅을 전담하는 브랜드이자,\n당사의 공연을 사랑해 주시는 마니아분들들을 지칭합니다.\n\n해븐마니아 분들을 위한 다양한 공연 콘텐츠를 제공해 드리겠습니다 :)\n많은 관심과 사랑 부탁드립니다!\n"
    }
  },
  "contentDetails": {
    "relatedPlaylists": {
      "likes": "",
      "uploads": "UUfxGrUvr10MjaCVKE_HVGgw"
    }
  },
  "statistics": {
    "viewCount": "3596981",
    "subscriberCount": "6200",
    "hiddenSubscriberCount": false,
    "videoCount": "514"
  },
  "topicDetails": {
    "topicIds": [
      "/m/019_rr",
      "/m/04rlf",
      "/m/02jjt",
      "/m/05qjc"
    ],
    "topicCategories": [
      "https://en.wikipedia.org/wiki/Lifestyle_(sociology)",
      "https://en.wikipedia.org/wiki/Music",
      "https://en.wikipedia.org/wiki/Entertainment",
      "https://en.wikipedia.org/wiki/Performing_arts"
    ]
  },
  "status": {
    "privacyStatus": "public",
    "isLinked": true,
    "longUploadsStatus": "longUploadsUnspecified"
  },
  "brandingSettings": {
    "channel": {
      "title": "해븐마니아",
      "description": "'해븐마니아'는 공연에 특화된 서비스와 마케팅을 전담하는 브랜드이자,\n당사의 공연을 사랑해 주시는 마니아분들들을 지칭합니다.\n\n해븐마니아 분들을 위한 다양한 공연 콘텐츠를 제공해 드리겠습니다 :)\n많은 관심과 사랑 부탁드립니다!\n",
      "unsubscribedTrailer": "_ZU49MsUnfg"
    }
  }
}

## 4. 필드별 상세 확인

### 4-1. snippet (기본 정보)

In [150]:
rows = []
for item in response['items']:
    s = item.get('snippet', {})
    rows.append({
        # ⭐ MUST — 채널 식별
        'channel_id':        item['id'],
        'title':             s.get('title'),            # ⭐ MUST  채널명
        'published_at':      s.get('publishedAt'),       # ⭐ MUST  채널 개설일 → 채널 나이 피처
        # ○ OPTIONAL
        'description':       s.get('description'),       # ○ 채널 설명
        'custom_url':        s.get('customUrl'),          # ○ @핸들
        'country':           s.get('country'),            # ○ 국가 코드
        'default_language':  s.get('defaultLanguage'),   # ○ 기본 언어
        'thumbnail_default': s.get('thumbnails', {}).get('default', {}).get('url'),
        'thumbnail_high':    s.get('thumbnails', {}).get('high', {}).get('url'),
    })

pd.DataFrame(rows)

,channel_id,title,published_at,description,custom_url,country,default_language,thumbnail_default,thumbnail_high
0,UCfxGrUvr10MjaCVKE_HVGgw,해븐마니아,2015-01-22T07:45:37Z,"'해븐마니아'는 공연에 특화된 서비스와 마케팅을 전담하는 브랜드이자,\n당사의 공연...",@heavenmania,None,None,https://yt3.ggpht.com/55KJ50QbibFs9uau5nBklKkY...,https://yt3.ggpht.com/55KJ50QbibFs9uau5nBklKkY...
1,UCFHt4Drs8lmyd-aUsBqM5uQ,나반장,2013-08-26T00:49:17Z,.\n\n,@nabanjang,KR,None,https://yt3.ggpht.com/721WXcieL5KhhgZ8_fYImMOH...,https://yt3.ggpht.com/721WXcieL5KhhgZ8_fYImMOH...
2,UCG6jmnh5Qw2SZYIPsN2Azfw,Online Topik,2020-08-10T09:34:29.926778Z,Let's Learn Korean Language \nAll about Korea\...,@onlinetopik267,None,mn,https://yt3.ggpht.com/GhqtCI13KlpEWK2YWRYMLOoK...,https://yt3.ggpht.com/GhqtCI13KlpEWK2YWRYMLOoK...
3,UC5p-SkOSlkZRiF6CRdIFJvw,TOY AMIGO,2015-12-15T07:21:32Z,TOY (장난감) + AMiGO (친구를 뜻하는 스페인어)\n\n\n스톱모션 촬영으...,@toyamigo,KR,ko,https://yt3.ggpht.com/ytc/AIdro_nqZnX5EX5dmiDl...,https://yt3.ggpht.com/ytc/AIdro_nqZnX5EX5dmiDl...
4,UC76R9DL1NjD7aLr_C3eueLA,이상한 나라의 신기한 개발자,2018-12-25T11:04:20Z,재미 있개 풀어가는 개발 이야기 : 질문해서 잔소리 듣고 싶은곳 메일 : wears...,@이상한나라의신기한개,KR,None,https://yt3.ggpht.com/ytc/AIdro_nhdZUiV_8nkjuf...,https://yt3.ggpht.com/ytc/AIdro_nhdZUiV_8nkjuf...
5,UCktQ-dRsgT6IYjKXqw7fTCQ,じゃぴ,2012-10-28T04:32:01Z,こんにちは。ショート動画を中心に投稿しています。♥️🌷\n,@j_lee-y3m,JP,None,https://yt3.ggpht.com/E-3jrZbZPTDrW19QG_aN0FYe...,https://yt3.ggpht.com/E-3jrZbZPTDrW19QG_aN0FYe...
6,UCz0mNYCcfvetgrS7h0H-WcQ,柯柯yeliz,2012-07-07T15:27:39Z,HELLO!! 我是柯柯YELIZ\n喜歡分享我的生活，希望你們喜歡我的生活唷~\n👉🏻合作...,@yeliz5246,None,zh-TW,https://yt3.ggpht.com/ytc/AIdro_kk6zdssPkCdv9P...,https://yt3.ggpht.com/ytc/AIdro_kk6zdssPkCdv9P...
7,UC-Id9P16Dnutun3wual1fcA,출동 도시의 영웅들 (한국말),2014-10-30T13:39:02Z,도시의 영웅들에 오신 것을 환영합니다. \n\n도시의 친구들과 신나는 모험을 떠나...,@출동도시의영웅들한국,None,None,https://yt3.ggpht.com/ytc/AIdro_lEyDtlNsjf10Be...,https://yt3.ggpht.com/ytc/AIdro_lEyDtlNsjf10Be...
8,UC20IAd2RgxMkSNAbiRVMdGQ,한국어 노래 가사 - KTrot 365,2024-10-11T09:27:04.152027Z,"안녕하세요 트롯을 사랑하는 여러분! 오늘은 여러분의 마음을 사로잡을 특별한 영상, ...",@ktrot365,KR,None,https://yt3.ggpht.com/0GX4v0oNUokCeZYD0wuOmz_V...,https://yt3.ggpht.com/0GX4v0oNUokCeZYD0wuOmz_V...
9,UCGqrzELBIpH6kfgJsNcZgeQ,마즐래 WGworking,2012-11-07T16:32:36Z,재활용 나무젓가락으로 공예를 하고 있습니다.\nRecycled wood chopst...,@wgworking,KR,ko,https://yt3.ggpht.com/zLynQDtAgzLrDbm9asq6d067...,https://yt3.ggpht.com/zLynQDtAgzLrDbm9asq6d067...
10,UCHHmDl_k97jLSOYbKEflr5Q,중고차인사이드,2017-02-26T09:02:27Z,,@중고차인사이드,None,None,https://yt3.ggpht.com/ytc/AIdro_kebbIPZZLlCScL...,https://yt3.ggpht.com/ytc/AIdro_kebbIPZZLlCScL...
11,UCopSrNAWJnzm4ETOS4mXHnw,이야기마을 잉코(Storytown EngKor),2017-10-30T03:34:48Z,Welcome to Storytown EngKor.\n\n이야기마을 잉코(Story...,@storytownengkor8349,None,None,https://yt3.ggpht.com/ytc/AIdro_kYLUoAfe5TkPP7...,https://yt3.ggpht.com/ytc/AIdro_kYLUoAfe5TkPP7...
12,UCx7ThnRlyrSSiNCLIZI0aqQ,가원,2012-12-12T11:25:54Z,영상 일기장\nVideo Diary,@gawon,KR,None,https://yt3.ggpht.com/ZTp-ueGAigDuccUeBT33fA_A...,https://yt3.ggpht.com/ZTp-ueGAigDuccUeBT33fA_A...
13,UCW53Pedlt62rx5zuTRZKUow,어니언스onience,2016-09-14T11:21:41Z,구독해서 해볼 거 하나도 없는 어니언스! 인사드려요!! (와)\n어렵고 복잡한 정치...,@onience,KR,None,https://yt3.ggpht.com/ytc/AIdro_nN_z9elcSg74DC...,https://yt3.ggpht.com/ytc/AIdro_nN_z9elcSg74DC...
14,UCa98sUKOO-0ZoqmnOlY1i2g,천재아시안,2013-11-14T11:58:27Z,ultraman\ngodzilla\n,@ultrama,KR,None,https://yt3.ggpht.com/ytc/AIdro_mw7UVmJjTBS2CS...,https://yt3.ggpht.com/ytc/AIdro_mw7UVmJjTBS2CS...
15,UC0CN1kbW3RuSz60bE9ELHcw,네웃음을책임져,2016-01-19T18:00:06Z,\n,@smlie1327,KR,None,https://yt3.ggpht.com/1VDfAjXuPoePoPa-ehxIfHWk...,https://yt3.ggpht.com/1VDfAjXuPoePoPa-ehxIfHWk...
16,UC6oN6MLpxu2CbCCIsQET0iA,L'HIBOU이부,2012-11-12T14:37:21Z,"낮에는 회사를 다니고, \n밤에는 가죽을 만져요.\n\n낡고 오래된 것을 사랑하며\...",@lhibou,KR,None,https://yt3.ggpht.com/ytc/AIdro_ndF3ZZvGudULcJ...,https://yt3.ggpht.com/ytc/AIdro_ndF3ZZvGudULcJ...
17,UCYhXoMjqKjfbh_bg57CyTIQ,꾸꾸야놀자 Let's play KooKooya,2015-02-17T06:37:28Z,엄마와 아이가 함께 즐기는 놀이TV!!\n\n꾸꾸야놀자는\n엄마와 아이가 함께 따라...,@kookooya,KR,ko,https://yt3.ggpht.com/ytc/AIdro_mznUrVqG5LNTKR...,https://yt3.ggpht.com/ytc/AIdro_mznUrVqG5LNTKR...
18,UC66duPrHKb_TJge0IL8x_9g,BROKENPASTEL,2015-12-25T16:18:51Z,𝗡𝗢𝗧𝗛𝗜𝗡𝗚 𝗕𝗨𝗧 𝗧𝗛𝗘 𝗕𝗘𝗔𝗧.\nContact: flashback9903@...,@brokenpastel,None,ko,https://yt3.ggpht.com/Ch0T6ayUFntG2OA2gWUkf2ws...,https://yt3.ggpht.com/Ch0T6ayUFntG2OA2gWUkf2ws...
19,UCVkE4YghTzGO61KHRsmffag,IncrediTales - 한국어,2022-03-10T23:00:36.875221Z,"신데렐라, 스노우하이트, 라푼젤, 로빈 후드... 모두가 이런 이야기를 좋아하지만,...",@increditales_korean,KR,None,https://yt3.ggpht.com/mRXRQaTW7EHXfEReLjvT3RB6...,https://yt3.ggpht.com/mRXRQaTW7EHXfEReLjvT3RB6...
20,UCCtKt-yPCrhLd6nlgJQc4RQ,꽃세히 sayblossom,2014-05-04T07:40:51Z,어쩌다보니\n엄마가 된 꽃세히입니다🥰\n\n좋아하는 것 그리고 일상을 함께해요💛,@sayblossom,KR,None,https://yt3.ggpht.com/ytc/AIdro_lABNVmOv0MFxXP...,https://yt3.ggpht.com/ytc/AIdro_lABNVmOv0MFxXP...
21,UCIb_O9AwrmaCXquQJ0TIVdw,귀공master,2018-11-20T01:29:16Z,안녕하세요. \n귀공 마스터의 \n마스터 김 입니다.\n\n귀공 마스터란?\n귀금속...,@master-df2od,None,None,https://yt3.ggpht.com/ytc/AIdro_lrc-pzdjqf7ErG...,https://yt3.ggpht.com/ytc/AIdro_lrc-pzdjqf7ErG...
22,UC-MAo6JvPw49wWJzTePGF5Q,죠맘동화tv,2017-03-04T16:41:57Z,(죠맘tv) 행복한 동화나라/전래동화/ 재미있는이야기\n잠자리동화/구연동화,@tv-mi4df,KR,None,https://yt3.ggpht.com/ytc/AIdro_komWVqcii6ibpo...,https://yt3.ggpht.com/ytc/AIdro_komWVqcii6ibpo...
23,UCHzxtmQhWwhFajAhtgfumKg,민주평화당TV,2018-02-09T07:57:27Z,민생당 공식 유튜브 채널입니다. \n민생을 먼저 생각하는 정치 하겠습니다.,@tv-rd7wm,KR,None,https://yt3.ggpht.com/ytc/AIdro_mBtY543BmIIK_o...,https://yt3.ggpht.com/ytc/AIdro_mBtY543BmIIK_o...
24,UCPQ887rCYjOSSxN6nXqAojg,-장난감 가게 점장-장점장,2019-02-28T06:01:10Z,\n\n안녕하세요? 장난감 가게 점장 장점장 입니다. \n\n저희 가게 취급 제품은...,@---kx3ww,KR,None,https://yt3.ggpht.com/ytc/AIdro_mnY_yZmhtnDgNK...,https://yt3.ggpht.com/ytc/AIdro_mnY_yZmhtnDgNK...
25,UCfVqqxdFMvN4f0-isg0_bbw,(방가샷bangga_shoot),2018-08-02T07:12:26Z,🔥 KBL 레전드 방성윤이 들려주는 진짜 농구 이야기!\n코트 위의 치열한 순간부터...,@user-bangga_shoot,KR,None,https://yt3.ggpht.com/WCZ1Yk6WDbLI0WnH0N_VgBR7...,https://yt3.ggpht.com/WCZ1Yk6WDbLI0WnH0N_VgBR7...
26,UCgXzwGNQLKQ4LA4XmWYWuvw,기타치는다람띠,2016-01-31T20:16:31Z,취미생활 연주기록,@daramddi,KR,None,https://yt3.ggpht.com/RyFi2OV9_0FhNrAuP_pUFrsD...,https://yt3.ggpht.com/RyFi2OV9_0FhNrAuP_pUFrsD...
27,UCkmNa3uEggjZis2eYbaXXnA,케민,2013-07-21T04:17:45Z,카톡 : kei01021221\n투네이션 : https://toon.at/donat...,@케민,KR,None,https://yt3.ggpht.com/lHUns2KocyWU0trwkw8i1b10...,https://yt3.ggpht.com/lHUns2KocyWU0trwkw8i1b10...
28,UCstHL8TQy5hjCSIxK370aow,Strawberry Toonz,2020-02-17T08:21:03.305346Z,Memes + Animation = Fun! 🎉\nThat’s what we do ...,@strawberrytoonz,KR,en,https://yt3.ggpht.com/7KU7vCP7NFB93sp7h_8zX3K9...,https://yt3.ggpht.com/7KU7vCP7NFB93sp7h_8zX3K9...
29,UChC6A-YfVfQ9jbqG5zb4gjw,음악 같은 사진 이야기,2012-08-01T13:24:13Z,필름 카메라와 함께_,@음악같은사진이야기,KR,None,https://yt3.ggpht.com/Vi_Ju_r-oWQ1Yd8Tq2v9bidz...,https://yt3.ggpht.com/Vi_Ju_r-oWQ1Yd8Tq2v9bidz...
30,UC7SSJS5huELNkaI6XhoNpNw,Ricksoft,2025-08-14T16:34:46.779612Z,Welcome to Ricksoft! \nStep into a nostalgic c...,@ricksoftmusic,MX,None,https://yt3.ggpht.com/mqUJHdqXBjsq0QXLddOxQ8x1...,https://yt3.ggpht.com/mqUJHdqXBjsq0QXLddOxQ8x1...
31,UCc8RR9yJEKVvP31OWBqhIjg,RFA FAN,2018-03-09T12:06:15Z,Movie Drama,@neayplochfunny,KR,None,https://yt3.ggpht.com/ytc/AIdro_k5kGybp5THnAfD...,https://yt3.ggpht.com/ytc/AIdro_k5kGybp5THnAfD...
32,UC3QWksal35X_nSXE8jC59_A,ELCANTO(엘칸토),2019-05-27T05:51:05Z,엘칸토 & 인텐스 & 마쯔 공식 유튜브 채널\n\n\n,@elcanto1957,KR,None,https://yt3.ggpht.com/BhazvGXj2XQhEu1ni7JqRddF...,https://yt3.ggpht.com/BhazvGXj2XQhEu1ni7JqRddF...
33,UC9mpnu1x96y7utLpnYyU6kw,Rocky Byun 변남석 중심잡기,2010-02-12T05:08:02Z,중심잡기예술가 변남석입니다.\n나의 인스타그램 피싱당했습니다. 전에 rockybyu...,@balanceace,KR,None,https://yt3.ggpht.com/y8oQFx1zw8UmVuVu84-tbMXY...,https://yt3.ggpht.com/y8oQFx1zw8UmVuVu84-tbMXY...
34,UCGGhcGI2JzKmtpSUkqSm7HQ,간다고,2018-10-29T07:50:39Z,"산을 주제로 백패킹,등산 관련 영상을 만들고 있습니다 \n\n백패킹 등산 비박 트레...",@간다고,KR,None,https://yt3.ggpht.com/ytc/AIdro_mWKYr558C63oOF...,https://yt3.ggpht.com/ytc/AIdro_mWKYr558C63oOF...
35,UCsnakEva6XIr8rf0P8R_vBQ,애슐리Ashley,2015-08-05T14:34:13Z,"❤️ 여성 뷰티, 운동 & 여행 콘텐츠 제작하고 있어요 😊\n\n",@ash_33,KR,None,https://yt3.ggpht.com/ytc/AIdro_mF52N9e4dgYPZK...,https://yt3.ggpht.com/ytc/AIdro_mF52N9e4dgYPZK...
36,UCKcwMdtuEELC4hn_fUlfVrA,꿍꿍TV,2019-05-01T20:59:51Z,안녕하세요! \n짝꿍 + 까꿍 = 꿍꿍TV 입니다. ♥\n\n사랑스러움이 가득한 아...,@cutiebaby,KR,None,https://yt3.ggpht.com/cv1bFdbVTlFGH5ooheO7t--2...,https://yt3.ggpht.com/cv1bFdbVTlFGH5ooheO7t--2...
37,UC9hWQRe4QrUivXN3VO2iuMA,코드종,2018-06-09T08:48:31Z,웹이나 모바일 앱 서비스를 개발할 때 자주 쓰지만 알쏭달쏭한 것들에 대해 가능한 쉽...,@codejong,None,None,https://yt3.ggpht.com/TP6zx60Eojolt7MGNJg153xy...,https://yt3.ggpht.com/TP6zx60Eojolt7MGNJg153xy...
38,UCH7XQue96n6LH2EBwcp5_Xw,12거는 고양이,2014-01-14T11:46:48Z,목요일과 토요일 아침 10시!🕙\n11묘와 집사의 달콤하고 유쾌한 영상이 찾아옵니다...,@12거는고양이,KR,ko,https://yt3.ggpht.com/ytc/AIdro_l4k6WgzP06-n09...,https://yt3.ggpht.com/ytc/AIdro_l4k6WgzP06-n09...
39,UC7ddGHlf5sUc3w3yeMRqTLA,낚튜브 [낚시의 궁금한 모든것]_NotTube,2014-03-10T02:30:38Z,낚시의 궁금한 모든것! 낚튜브!!!낚시&캠핑 종합 아웃도어 채널~ \n꼭 알아야하는...,@nottube,KR,None,https://yt3.ggpht.com/3yWX_DT8QKO10nOh7R_FFgoy...,https://yt3.ggpht.com/3yWX_DT8QKO10nOh7R_FFgoy...
40,UCS_GfKlHjjFwgIqGyZOwbtA,방랑이고싶다 BangLang,2012-12-09T02:28:43Z,하고 싶은 대로 살아보려 노력하는 사서고생쟁이 브이로그입니다.,@banglangs,KR,None,https://yt3.ggpht.com/vBsxQKvA36WKOAZy4Y6459oy...,https://yt3.ggpht.com/vBsxQKvA36WKOAZy4Y6459oy...
41,UCJ2jmRmeLWFtVQQPsut9v8w,스타토이,2016-06-11T02:17:39Z,안녕하세요. 스타토이입니다! ^^\n엉뚱한 스타토이 친구들의 박진감 넘치고 재미있는...,@스타토이,KR,None,https://yt3.ggpht.com/ytc/AIdro_nXDUW7YStv6kVj...,https://yt3.ggpht.com/ytc/AIdro_nXDUW7YStv6kVj...
42,UCS7_uGiAocfn0JGrJliGVrA,EORI TV,2013-04-24T08:01:17Z,전래동화 세계명작동화 안데르센동화 등의 어린이들에게 필요한 인성을 길러주는 동화애니...,@eoritv,None,None,https://yt3.ggpht.com/ytc/AIdro_mAVtF90FNTrQsN...,https://yt3.ggpht.com/ytc/AIdro_mAVtF90FNTrQsN...
43,UCPvt1dbhi23-FTpGYZrmpLw,부산희야TV(Korean Ghost Tracker),2011-02-11T13:36:34Z,BJ부산희야\n\n2017 년 현제 4년차 흉가 방송 스트리머로 활동중\n\n귀신을...,@heeyaa,KR,None,https://yt3.ggpht.com/n9l396t3hVTL6ThoUXyvzMOa...,https://yt3.ggpht.com/n9l396t3hVTL6ThoUXyvzMOa...
44,UCUEAfMdSYiXDfRVxdfqAQrg,나승빈 선생님_함께 있어 행복한 우리_,2012-07-19T12:51:05Z,"함께 있어 행복한 우리. 함행우 학급살이와 수업, 놀이와 체육 영상 입니다. 많이 ...",@nsbking47,KR,ko,https://yt3.ggpht.com/ytc/AIdro_lq4sFcPXtVZvY8...,https://yt3.ggpht.com/ytc/AIdro_lq4sFcPXtVZvY8...
45,UC8RUkja-IDFu10i5Rq3LX0A,arenaKorea_아레나코리아,2012-01-27T00:24:20Z,"BEYOND THE WATER, ARENA\n",@arenakorea,KR,None,https://yt3.ggpht.com/5z_ZJq8EcQklbfZ5JI4SYttI...,https://yt3.ggpht.com/5z_ZJq8EcQklbfZ5JI4SYttI...
46,UCnss3Bsz1g9XpJBNM62vlWA,디아블로 이모탈,2021-05-04T16:03:12.463643Z,디아블로 이모탈은 모바일 대규모 다중 사용자 온라인 액션 롤 플레잉 게임으로 PC와...,@diabloimmortalkr,KR,None,https://yt3.ggpht.com/PKpL2bhoKXyNRpRgqetlvTuP...,https://yt3.ggpht.com/PKpL2bhoKXyNRpRgqetlvTuP...
47,UCA7WtDf9bYuRW1BowR00e6g,고뎅,2016-10-09T08:38:55Z,크리에이터 고뎅입니다!\n1. 리그오브레전드(LOL) 서포터 플레이\n2. 배틀그라...,@고뎅,KR,None,https://yt3.ggpht.com/ytc/AIdro_lZQ66bTtMifLJb...,https://yt3.ggpht.com/ytc/AIdro_lZQ66bTtMifLJb...
48,UCzDLR2GTRqNsIFSnLacmdKg,조응천 중계석,2016-07-01T01:05:35Z,후원: 농협 301-0385-8398-31 조응천후원회(경기도지사선거)\n\n❤언제...,@chopros,KR,ko,https://yt3.ggpht.com/PNCYDmQoEHoPhjyXkFvRld_J...,https://yt3.ggpht.com/PNCYDmQoEHoPhjyXkFvRld_J...

### 4-2. contentDetails — ⭐ uploads 플레이리스트 ID (영상 수집 핵심)

In [151]:
rows = []
for item in response['items']:
    cd = item.get('contentDetails', {}).get('relatedPlaylists', {})
    rows.append({
        'channel_id':       item['id'],
        'uploads_playlist': cd.get('uploads'),   # ⭐ MUST  영상 목록 수집에 필수
        'likes_playlist':   cd.get('likes'),      # ○ 좋아요 재생목록
    })

df_content = pd.DataFrame(rows)
df_content

                  channel_id          uploads_playlist likes_playlist
0   UCfxGrUvr10MjaCVKE_HVGgw  UUfxGrUvr10MjaCVKE_HVGgw
1   UCFHt4Drs8lmyd-aUsBqM5uQ  UUFHt4Drs8lmyd-aUsBqM5uQ
2   UCG6jmnh5Qw2SZYIPsN2Azfw  UUG6jmnh5Qw2SZYIPsN2Azfw
3   UC5p-SkOSlkZRiF6CRdIFJvw  UU5p-SkOSlkZRiF6CRdIFJvw
4   UC76R9DL1NjD7aLr_C3eueLA  UU76R9DL1NjD7aLr_C3eueLA
5   UCktQ-dRsgT6IYjKXqw7fTCQ  UUktQ-dRsgT6IYjKXqw7fTCQ
6   UCz0mNYCcfvetgrS7h0H-WcQ  UUz0mNYCcfvetgrS7h0H-WcQ
7   UC-Id9P16Dnutun3wual1fcA  UU-Id9P16Dnutun3wual1fcA
8   UC20IAd2RgxMkSNAbiRVMdGQ  UU20IAd2RgxMkSNAbiRVMdGQ
9   UCGqrzELBIpH6kfgJsNcZgeQ  UUGqrzELBIpH6kfgJsNcZgeQ
10  UCHHmDl_k97jLSOYbKEflr5Q  UUHHmDl_k97jLSOYbKEflr5Q
11  UCopSrNAWJnzm4ETOS4mXHnw  UUopSrNAWJnzm4ETOS4mXHnw
12  UCx7ThnRlyrSSiNCLIZI0aqQ  UUx7ThnRlyrSSiNCLIZI0aqQ
13  UCW53Pedlt62rx5zuTRZKUow  UUW53Pedlt62rx5zuTRZKUow
14  UCa98sUKOO-0ZoqmnOlY1i2g  UUa98sUKOO-0ZoqmnOlY1i2g
15  UC0CN1kbW3RuSz60bE9ELHcw  UU0CN1kbW3RuSz60bE9ELHcw
16  UC6oN6MLpxu2CbCCIsQET0iA  UU6oN6MLpxu2CbCCIsQET0iA
17  UCYhXoMjqKjfbh_bg57CyTIQ  UUYhXoMjqKjfbh_bg57CyTIQ
18  UC66duPrHKb_TJge0IL8x_9g  UU66duPrHKb_TJge0IL8x_9g
19  UCVkE4YghTzGO61KHRsmffag  UUVkE4YghTzGO61KHRsmffag
20  UCCtKt-yPCrhLd6nlgJQc4RQ  UUCtKt-yPCrhLd6nlgJQc4RQ
21  UCIb_O9AwrmaCXquQJ0TIVdw  UUIb_O9AwrmaCXquQJ0TIVdw
22  UC-MAo6JvPw49wWJzTePGF5Q  UU-MAo6JvPw49wWJzTePGF5Q
23  UCHzxtmQhWwhFajAhtgfumKg  UUHzxtmQhWwhFajAhtgfumKg
24  UCPQ887rCYjOSSxN6nXqAojg  UUPQ887rCYjOSSxN6nXqAojg
25  UCfVqqxdFMvN4f0-isg0_bbw  UUfVqqxdFMvN4f0-isg0_bbw
26  UCgXzwGNQLKQ4LA4XmWYWuvw  UUgXzwGNQLKQ4LA4XmWYWuvw
27  UCkmNa3uEggjZis2eYbaXXnA  UUkmNa3uEggjZis2eYbaXXnA
28  UCstHL8TQy5hjCSIxK370aow  UUstHL8TQy5hjCSIxK370aow
29  UChC6A-YfVfQ9jbqG5zb4gjw  UUhC6A-YfVfQ9jbqG5zb4gjw
30  UC7SSJS5huELNkaI6XhoNpNw  UU7SSJS5huELNkaI6XhoNpNw
31  UCc8RR9yJEKVvP31OWBqhIjg  UUc8RR9yJEKVvP31OWBqhIjg
32  UC3QWksal35X_nSXE8jC59_A  UU3QWksal35X_nSXE8jC59_A
33  UC9mpnu1x96y7utLpnYyU6kw  UU9mpnu1x96y7utLpnYyU6kw
34  UCGGhcGI2JzKmtpSUkqSm7HQ  UUGGhcGI2JzKmtpSUkqSm7HQ
35  UCsnakEva6XIr8rf0P8R_vBQ  UUsnakEva6XIr8rf0P8R_vBQ
36  UCKcwMdtuEELC4hn_fUlfVrA  UUKcwMdtuEELC4hn_fUlfVrA
37  UC9hWQRe4QrUivXN3VO2iuMA  UU9hWQRe4QrUivXN3VO2iuMA
38  UCH7XQue96n6LH2EBwcp5_Xw  UUH7XQue96n6LH2EBwcp5_Xw
39  UC7ddGHlf5sUc3w3yeMRqTLA  UU7ddGHlf5sUc3w3yeMRqTLA
40  UCS_GfKlHjjFwgIqGyZOwbtA  UUS_GfKlHjjFwgIqGyZOwbtA
41  UCJ2jmRmeLWFtVQQPsut9v8w  UUJ2jmRmeLWFtVQQPsut9v8w
42  UCS7_uGiAocfn0JGrJliGVrA  UUS7_uGiAocfn0JGrJliGVrA
43  UCPvt1dbhi23-FTpGYZrmpLw  UUPvt1dbhi23-FTpGYZrmpLw
44  UCUEAfMdSYiXDfRVxdfqAQrg  UUUEAfMdSYiXDfRVxdfqAQrg
45  UC8RUkja-IDFu10i5Rq3LX0A  UU8RUkja-IDFu10i5Rq3LX0A
46  UCnss3Bsz1g9XpJBNM62vlWA  UUnss3Bsz1g9XpJBNM62vlWA
47  UCA7WtDf9bYuRW1BowR00e6g  UUA7WtDf9bYuRW1BowR00e6g
48  UCzDLR2GTRqNsIFSnLacmdKg  UUzDLR2GTRqNsIFSnLacmdKg

### 4-3. statistics — ⭐ 구독자·조회수·영상 수

In [152]:
rows = []
for item in response['items']:
    st = item.get('statistics', {})
    rows.append({
        'channel_id':              item['id'],
        'subscriber_count':        st.get('subscriberCount'),         # ⭐ MUST  구독자 수
        'view_count':              st.get('viewCount'),                # ⭐ MUST  총 채널 조회수
        'video_count':             st.get('videoCount'),               # ⭐ MUST  총 영상 수
        'hidden_subscriber_count': st.get('hiddenSubscriberCount'),   # ○ 구독자 수 비공개 여부
    })

pd.DataFrame(rows)

,channel_id,subscriber_count,view_count,video_count,hidden_subscriber_count
0,UCfxGrUvr10MjaCVKE_HVGgw,6200,3596981,514,False
1,UCFHt4Drs8lmyd-aUsBqM5uQ,6470,227365,22,False
2,UCG6jmnh5Qw2SZYIPsN2Azfw,6190,269277,207,False
3,UC5p-SkOSlkZRiF6CRdIFJvw,6170,8474110,146,False
4,UC76R9DL1NjD7aLr_C3eueLA,6500,1367378,1032,False
5,UCktQ-dRsgT6IYjKXqw7fTCQ,6060,27698,9,False
6,UCz0mNYCcfvetgrS7h0H-WcQ,6740,275423,10,False
7,UC-Id9P16Dnutun3wual1fcA,6300,6380185,98,False
8,UC20IAd2RgxMkSNAbiRVMdGQ,7640,912187,66,False
9,UCGqrzELBIpH6kfgJsNcZgeQ,6280,1120420,129,False
10,UCHHmDl_k97jLSOYbKEflr5Q,6330,2624644,5,False
11,UCopSrNAWJnzm4ETOS4mXHnw,6150,877226,182,False
12,UCx7ThnRlyrSSiNCLIZI0aqQ,6180,1076393,264,False
13,UCW53Pedlt62rx5zuTRZKUow,6170,9988,12,False
14,UCa98sUKOO-0ZoqmnOlY1i2g,6130,3010149,433,False
15,UC0CN1kbW3RuSz60bE9ELHcw,6280,238786,18,False
16,UC6oN6MLpxu2CbCCIsQET0iA,6730,331996,21,False
17,UCYhXoMjqKjfbh_bg57CyTIQ,6570,2106526,170,False
18,UC66duPrHKb_TJge0IL8x_9g,6330,7713661,19490,False
19,UCVkE4YghTzGO61KHRsmffag,6630,5527964,285,False
20,UCCtKt-yPCrhLd6nlgJQc4RQ,6520,838618,61,False
21,UCIb_O9AwrmaCXquQJ0TIVdw,6660,398177,51,False
22,UC-MAo6JvPw49wWJzTePGF5Q,6160,1639439,91,False
23,UCHzxtmQhWwhFajAhtgfumKg,6660,3032739,1841,False
24,UCPQ887rCYjOSSxN6nXqAojg,6280,2475774,642,False
25,UCfVqqxdFMvN4f0-isg0_bbw,6360,2803828,299,False
26,UCgXzwGNQLKQ4LA4XmWYWuvw,6000,95933,4,False
27,UCkmNa3uEggjZis2eYbaXXnA,7720,8999075,3073,False
28,UCstHL8TQy5hjCSIxK370aow,6760,269539,8,False
29,UChC6A-YfVfQ9jbqG5zb4gjw,6230,387698,38,False
30,UC7SSJS5huELNkaI6XhoNpNw,6490,3581389,25,False
31,UCc8RR9yJEKVvP31OWBqhIjg,6350,886249,42,False
32,UC3QWksal35X_nSXE8jC59_A,6500,883676,161,False
33,UC9mpnu1x96y7utLpnYyU6kw,6200,2754400,346,False
34,UCGGhcGI2JzKmtpSUkqSm7HQ,6310,1091748,95,False
35,UCsnakEva6XIr8rf0P8R_vBQ,6500,1026052,127,False
36,UCKcwMdtuEELC4hn_fUlfVrA,6200,3775714,80,False
37,UC9hWQRe4QrUivXN3VO2iuMA,6530,259083,30,False
38,UCH7XQue96n6LH2EBwcp5_Xw,6550,1688145,564,False
39,UC7ddGHlf5sUc3w3yeMRqTLA,6030,2768646,263,False
40,UCS_GfKlHjjFwgIqGyZOwbtA,5980,20517,28,False
41,UCJ2jmRmeLWFtVQQPsut9v8w,5990,7315300,68,False
42,UCS7_uGiAocfn0JGrJliGVrA,6470,9197522,153,False
43,UCPvt1dbhi23-FTpGYZrmpLw,6080,2023460,389,False
44,UCUEAfMdSYiXDfRVxdfqAQrg,6360,2389363,861,False
45,UC8RUkja-IDFu10i5Rq3LX0A,6780,12462307,174,False
46,UCnss3Bsz1g9XpJBNM62vlWA,6670,15171696,130,False
47,UCA7WtDf9bYuRW1BowR00e6g,6470,249443,1,False
48,UCzDLR2GTRqNsIFSnLacmdKg,7890,1851396,508,False

### 4-4. topicDetails (카테고리)

In [153]:
rows = []
for item in response['items']:
    td = item.get('topicDetails', {})
    rows.append({
        'channel_id':       item['id'],
        'topic_ids':        td.get('topicIds'),           # ○ Freebase 토픽 ID 목록
        'topic_categories': td.get('topicCategories'),   # ○ Wikipedia 카테고리 URL
    })

pd.DataFrame(rows)

,channel_id,topic_ids,topic_categories
0,UCfxGrUvr10MjaCVKE_HVGgw,"[/m/019_rr, /m/04rlf, /m/02jjt, /m/05qjc]",[https://en.wikipedia.org/wiki/Lifestyle_(soci...
1,UCFHt4Drs8lmyd-aUsBqM5uQ,"[/m/025zzc, /m/0bzvm2, /m/03hf_rm]","[https://en.wikipedia.org/wiki/Action_game, ht..."
2,UCG6jmnh5Qw2SZYIPsN2Azfw,"[/m/019_rr, /m/01k8wb]",[https://en.wikipedia.org/wiki/Lifestyle_(soci...
3,UC5p-SkOSlkZRiF6CRdIFJvw,"[/m/03glg, /m/019_rr]","[https://en.wikipedia.org/wiki/Hobby, https://..."
4,UC76R9DL1NjD7aLr_C3eueLA,[/m/098wr],[https://en.wikipedia.org/wiki/Society]
5,UCktQ-dRsgT6IYjKXqw7fTCQ,"[/m/0403l3g, /m/0bzvm2, /m/025zzc]",[https://en.wikipedia.org/wiki/Role-playing_vi...
6,UCz0mNYCcfvetgrS7h0H-WcQ,"[/g/120yrv6h, /m/019_rr]","[https://en.wikipedia.org/wiki/Tourism, https:..."
7,UC-Id9P16Dnutun3wual1fcA,"[/m/019_rr, /m/02vxn, /m/02jjt]",[https://en.wikipedia.org/wiki/Lifestyle_(soci...
8,UC20IAd2RgxMkSNAbiRVMdGQ,"[/m/04rlf, /m/028sqc]","[https://en.wikipedia.org/wiki/Music, https://..."
9,UCGqrzELBIpH6kfgJsNcZgeQ,"[/m/019_rr, /m/03glg]",[https://en.wikipedia.org/wiki/Lifestyle_(soci...
10,UCHHmDl_k97jLSOYbKEflr5Q,"[/m/07yv9, /m/019_rr]","[https://en.wikipedia.org/wiki/Vehicle, https:..."
11,UCopSrNAWJnzm4ETOS4mXHnw,"[/m/019_rr, /m/01k8wb]",[https://en.wikipedia.org/wiki/Lifestyle_(soci...
12,UCx7ThnRlyrSSiNCLIZI0aqQ,"[/m/02wbm, /m/019_rr]","[https://en.wikipedia.org/wiki/Food, https://e..."
13,UCW53Pedlt62rx5zuTRZKUow,"[/m/098wr, /m/05qt0]","[https://en.wikipedia.org/wiki/Society, https:..."
14,UCa98sUKOO-0ZoqmnOlY1i2g,"[/m/019_rr, /m/03glg]",[https://en.wikipedia.org/wiki/Lifestyle_(soci...
15,UC0CN1kbW3RuSz60bE9ELHcw,"[/m/07yv9, /m/09kqc, /m/02jjt, /m/019_rr]","[https://en.wikipedia.org/wiki/Vehicle, https:..."
16,UC6oN6MLpxu2CbCCIsQET0iA,"[/m/019_rr, /m/03glg, /m/032tl]",[https://en.wikipedia.org/wiki/Lifestyle_(soci...
17,UCYhXoMjqKjfbh_bg57CyTIQ,"[/m/03glg, /m/019_rr]","[https://en.wikipedia.org/wiki/Hobby, https://..."
18,UC66duPrHKb_TJge0IL8x_9g,"[/m/025zzc, /m/0bzvm2, /m/02hygl]","[https://en.wikipedia.org/wiki/Action_game, ht..."
19,UCVkE4YghTzGO61KHRsmffag,"[/m/02jjt, /m/02vxn]","[https://en.wikipedia.org/wiki/Entertainment, ..."
20,UCCtKt-yPCrhLd6nlgJQc4RQ,[/m/019_rr],[https://en.wikipedia.org/wiki/Lifestyle_(soci...
21,UCIb_O9AwrmaCXquQJ0TIVdw,"[/m/032tl, /m/019_rr, /m/03glg]","[https://en.wikipedia.org/wiki/Fashion, https:..."
22,UC-MAo6JvPw49wWJzTePGF5Q,"[/m/02vxn, /m/02jjt]","[https://en.wikipedia.org/wiki/Film, https://e..."
23,UCHzxtmQhWwhFajAhtgfumKg,"[/m/05qt0, /m/098wr]","[https://en.wikipedia.org/wiki/Politics, https..."
24,UCPQ887rCYjOSSxN6nXqAojg,"[/m/019_rr, /m/03glg]",[https://en.wikipedia.org/wiki/Lifestyle_(soci...
25,UCfVqqxdFMvN4f0-isg0_bbw,"[/m/019_rr, /m/018w8, /m/06ntj]",[https://en.wikipedia.org/wiki/Lifestyle_(soci...
26,UCgXzwGNQLKQ4LA4XmWYWuvw,[/m/04rlf],[https://en.wikipedia.org/wiki/Music]
27,UCkmNa3uEggjZis2eYbaXXnA,"[/m/025zzc, /m/0bzvm2, /m/0403l3g]","[https://en.wikipedia.org/wiki/Action_game, ht..."
28,UCstHL8TQy5hjCSIxK370aow,"[/m/028sqc, /m/02vxn, /m/02jjt, /m/064t9, /m/0...","[https://en.wikipedia.org/wiki/Music_of_Asia, ..."
29,UChC6A-YfVfQ9jbqG5zb4gjw,"[/m/03glg, /m/019_rr]","[https://en.wikipedia.org/wiki/Hobby, https://..."
30,UC7SSJS5huELNkaI6XhoNpNw,"[/m/04rlf, /m/064t9, /m/028sqc]","[https://en.wikipedia.org/wiki/Music, https://..."
31,UCc8RR9yJEKVvP31OWBqhIjg,"[/m/019_rr, /m/02vxn, /m/02jjt, /m/09kqc]",[https://en.wikipedia.org/wiki/Lifestyle_(soci...
32,UC3QWksal35X_nSXE8jC59_A,"[/m/019_rr, /m/032tl]",[https://en.wikipedia.org/wiki/Lifestyle_(soci...
33,UC9mpnu1x96y7utLpnYyU6kw,"[/m/03glg, /m/019_rr]","[https://en.wikipedia.org/wiki/Hobby, https://..."
34,UCGGhcGI2JzKmtpSUkqSm7HQ,"[/m/03glg, /m/019_rr, /g/120yrv6h]","[https://en.wikipedia.org/wiki/Hobby, https://..."
35,UCsnakEva6XIr8rf0P8R_vBQ,[/m/019_rr],[https://en.wikipedia.org/wiki/Lifestyle_(soci...
36,UCKcwMdtuEELC4hn_fUlfVrA,"[/m/03glg, /m/019_rr]","[https://en.wikipedia.org/wiki/Hobby, https://..."
37,UC9hWQRe4QrUivXN3VO2iuMA,"[/m/07c1v, /m/01k8wb, /m/019_rr]","[https://en.wikipedia.org/wiki/Technology, htt..."
38,UCH7XQue96n6LH2EBwcp5_Xw,"[/m/068hy, /m/019_rr]","[https://en.wikipedia.org/wiki/Pet, https://en..."
39,UC7ddGHlf5sUc3w3yeMRqTLA,"[/m/019_rr, /m/03glg, /m/068hy]",[https://en.wikipedia.org/wiki/Lifestyle_(soci...
40,UCS_GfKlHjjFwgIqGyZOwbtA,"[/m/019_rr, /m/02wbm]",[https://en.wikipedia.org/wiki/Lifestyle_(soci...
41,UCJ2jmRmeLWFtVQQPsut9v8w,"[/m/019_rr, /m/02jjt, /m/02vxn, /m/03glg]",[https://en.wikipedia.org/wiki/Lifestyle_(soci...
42,UCS7_uGiAocfn0JGrJliGVrA,"[/m/0f2f9, /m/02jjt, /m/02vxn]",[https://en.wikipedia.org/wiki/Television_prog...
43,UCPvt1dbhi23-FTpGYZrmpLw,"[/m/019_rr, /m/098wr]",[https://en.wikipedia.org/wiki/Lifestyle_(soci...
44,UCUEAfMdSYiXDfRVxdfqAQrg,"[/m/06ntj, /m/019_rr, /m/0kt51]","[https://en.wikipedia.org/wiki/Sport, https://..."
45,UC8RUkja-IDFu10i5Rq3LX0A,"[/m/032tl, /m/019_rr, /m/06ntj]","[https://en.wikipedia.org/wiki/Fashion, https:..."
46,UCnss3Bsz1g9XpJBNM62vlWA,"[/m/02ntfj, /m/025zzc, /m/0bzvm2, /m/0403l3g, ...",[https://en.wikipedia.org/wiki/Action-adventur...
47,UCA7WtDf9bYuRW1BowR00e6g,None,None
48,UCzDLR2GTRqNsIFSnLacmdKg,"[/m/05qt0, /m/098wr]","[https://en.wikipedia.org/wiki/Politics, https..."

### 4-5. brandingSettings

In [154]:
rows = []
for item in response['items']:
    ch = item.get('brandingSettings', {}).get('channel', {})
    img = item.get('brandingSettings', {}).get('image', {})
    rows.append({
        'channel_id':             item['id'],
        'keywords':               ch.get('keywords'),               # ○ 채널 키워드 (태그)
        'unsubscribed_trailer':   ch.get('unsubscribedTrailer'),    # ○ 구독 전 트레일러 영상 ID
        'banner_url':             img.get('bannerExternalUrl'),      # ○ 채널 배너 이미지 URL
    })

pd.DataFrame(rows)

,channel_id,keywords,unsubscribed_trailer,banner_url
0,UCfxGrUvr10MjaCVKE_HVGgw,None,_ZU49MsUnfg,None
1,UCFHt4Drs8lmyd-aUsBqM5uQ,None,None,https://yt3.googleusercontent.com/Zcbo_X0LGT8i...
2,UCG6jmnh5Qw2SZYIPsN2Azfw,None,None,https://yt3.googleusercontent.com/0ampQiH2e15a...
3,UC5p-SkOSlkZRiF6CRdIFJvw,토이아미고(toyamigo),d4UIq1LkFGw,https://yt3.googleusercontent.com/NSZe0SrYQBqC...
4,UC76R9DL1NjD7aLr_C3eueLA,이상한 나라의 신기한 개발자가 사는 세상 이야기 취업,ym6qR-yZZjY,https://yt3.googleusercontent.com/5RhV9q4wYdAV...
5,UCktQ-dRsgT6IYjKXqw7fTCQ,None,DQ7rpcDwKXA,None
6,UCz0mNYCcfvetgrS7h0H-WcQ,美妝 生活 美食 旅遊,None,https://yt3.googleusercontent.com/dPfg21R9DIxj...
7,UC-Id9P16Dnutun3wual1fcA,출동 도시의 영웅들,Gg-DVcGFkyU,https://yt3.googleusercontent.com/X0VgiBgphPGp...
8,UC20IAd2RgxMkSNAbiRVMdGQ,"트로트 트로트메들리 인기트로트 trot ktrot ""내일은 미스트롯"" 젊은트롯 ""요...",None,https://yt3.googleusercontent.com/HF4kFycnzw6I...
9,UCGqrzELBIpH6kfgJsNcZgeQ,DIY 총만들기 미니어처 나무공예 조각 공예 장인 만들기 무기 미니어쳐 수제 수공예...,x15ahhDNG-M,https://yt3.googleusercontent.com/zvj-QkaYKZAD...
10,UCHHmDl_k97jLSOYbKEflr5Q,중고차인사이드,None,https://yt3.googleusercontent.com/TgDyhsMvnWDg...
11,UCopSrNAWJnzm4ETOS4mXHnw,동화 읽기 Read Aloud,_Azs1ivtmNw,https://yt3.googleusercontent.com/ixA47QroN6JU...
12,UCx7ThnRlyrSSiNCLIZI0aqQ,"""화장품 BM"" ""일본어 원어민""",None,https://yt3.googleusercontent.com/d2ZJJcJr2Uq3...
13,UCW53Pedlt62rx5zuTRZKUow,지금 딱 필요한 어니언스,7aJdfnEYt4U,https://yt3.googleusercontent.com/BM7ti8nhj3to...
14,UCa98sUKOO-0ZoqmnOlY1i2g,"""고질라 토렌트"" ""고질라 콩 토렌트"" 울트라맨",uo1weu9aezE,https://yt3.googleusercontent.com/-KFZ9PM3bgHz...
15,UC0CN1kbW3RuSz60bE9ELHcw,유머 유머영상 유머숏츠 유머쇼츠 웃긴영상 웃긴짤 유머짤,None,https://yt3.googleusercontent.com/GknuPY4eMYH5...
16,UC6oN6MLpxu2CbCCIsQET0iA,가죽공예 가죽공예독학 핸드메이드 leathercraft leathergoods ha...,1EsH2MiPp2s,https://yt3.googleusercontent.com/8_G8uteLphEO...
17,UCYhXoMjqKjfbh_bg57CyTIQ,"키즈 아이와갈곳 아이와놀기 베이비송 ""korea baby"" ""korea toy"" 아...",oeDeQ9nnK80,https://yt3.googleusercontent.com/hN7UKeja2R9G...
18,UC66duPrHKb_TJge0IL8x_9g,None,None,https://yt3.googleusercontent.com/9ufj27e1wc5B...
19,UCVkE4YghTzGO61KHRsmffag,None,XtdVSzWOG9k,https://yt3.googleusercontent.com/D7KVxrHY35nw...
20,UCCtKt-yPCrhLd6nlgJQc4RQ,뷰티/패션/노하우/스타일/beauty/fashion/knowhow/style,None,https://yt3.googleusercontent.com/cVRoXBB1wbvZ...
21,UCIb_O9AwrmaCXquQJ0TIVdw,None,Cr4pguMtwK0,https://yt3.googleusercontent.com/4Si122qLJlMX...
22,UC-MAo6JvPw49wWJzTePGF5Q,잠자리동화모음 bedtimestories 명작동화모음 삼국유사 koreanfolkt...,-lD-Y6HxsOU,https://yt3.googleusercontent.com/LAPxU0YsVArD...
23,UCHzxtmQhWwhFajAhtgfumKg,#민생당 #정치 #정당 #민생정치 #김정기 #이관승 #최상임 #바른미래당 #민주평화...,yq5lCbG7Rjo,https://yt3.googleusercontent.com/6TAIGUXJ2t9b...
24,UCPQ887rCYjOSSxN6nXqAojg,하비 키덜트 취미 가면라이더 전대물 파워레인저 울트라맨 애니 로봇 메카닉 추억 장난...,p7AiQNX5hxg,https://yt3.googleusercontent.com/cm43-kZIhT8U...
25,UCfVqqxdFMvN4f0-isg0_bbw,"bangsungyoon 방성윤 방가 방성윤 농구선수 ""전 농구선수"" KBL ""대한민...",None,https://yt3.googleusercontent.com/je2TvPtZatLf...
26,UCgXzwGNQLKQ4LA4XmWYWuvw,None,mokm6Quegwo,None
27,UCkmNa3uEggjZis2eYbaXXnA,고전게임 공포게임 종합게임,None,https://yt3.googleusercontent.com/UN1YHXse0o1h...
28,UCstHL8TQy5hjCSIxK370aow,memes shorts animation funnyvideos funnyshorts...,None,https://yt3.googleusercontent.com/slWwGjNnCELb...
29,UChC6A-YfVfQ9jbqG5zb4gjw,"""필름 카메라"" ""필름 사진"" ""사진 강의""",IHw192dF9-c,https://yt3.googleusercontent.com/n2oi7vzYz8jT...
30,UC7SSJS5huELNkaI6XhoNpNw,None,None,https://yt3.googleusercontent.com/zo5_JeYNCtP1...
31,UCc8RR9yJEKVvP31OWBqhIjg,"Funny Comedy Troll Funnykids Nitean ""Khmer Fai...",O4EFKntqN2c,https://yt3.googleusercontent.com/YdMS114BBdo6...
32,UC3QWksal35X_nSXE8jC59_A,엘칸토 인텐스 deepp 마쯔 elcanto 엘칸토로퍼 엘칸토구두 여자구두 여자샌들...,Guv_Nfdz5V8,https://yt3.googleusercontent.com/CGyOWgjzdvyr...
33,UC9mpnu1x96y7utLpnYyU6kw,"""motivational lectures"" ""centering schools"" ""i...",0Tf3YmP1Yn4,https://yt3.googleusercontent.com/loghFSiTr7Rr...
34,UCGGhcGI2JzKmtpSUkqSm7HQ,백팩킹 등산 트레킹 여행,None,https://yt3.googleusercontent.com/yHq4cCB_BWM7...
35,UCsnakEva6XIr8rf0P8R_vBQ,뷰티 브이로그 다이어트 바디프로필 운동복 메이크업 스킨케어 동안비법 동안비결 여행,RxltW9ltrZ8,https://yt3.googleusercontent.com/94kSOmopi_zH...
36,UCKcwMdtuEELC4hn_fUlfVrA,육아 결혼 임신 출산 아기 baby wedding birthing pregnant ...,5ViDmgIS8BM,https://yt3.googleusercontent.com/kXnGzk8BLWmq...
37,UC9hWQRe4QrUivXN3VO2iuMA,javascript 개발 강좌 웹 모바일앱 app web,SNQVUIEjw8k,https://yt3.googleusercontent.com/3DBxZu-6bgwj...
38,UCH7XQue96n6LH2EBwcp5_Xw,반려동물 집사 고양이 아메리칸컬 벵갈 cat 猫 개냥이,N9qairBbPGc,https://yt3.googleusercontent.com/xJCZuBDZlowH...
39,UC7ddGHlf5sUc3w3yeMRqTLA,루어낚시 바다낚시 보트낚시 야엔 무늬오징어 문어낚시 낚시 Рыбалка 釣り Fis...,None,https://yt3.googleusercontent.com/uMQ4vCtmvNE8...
40,UCS_GfKlHjjFwgIqGyZOwbtA,"캠핑 세계여행 모로코생활 ""trip around the world"" travelin...",c1BJ1qHcM20,https://yt3.googleusercontent.com/gp3mLRojhG3k...
41,UCJ2jmRmeLWFtVQQPsut9v8w,뽀로로 장난감 애니,vDeYvPczo4E,https://yt3.googleusercontent.com/D-XIOLKZRokw...
42,UCS7_uGiAocfn0JGrJliGVrA,핑크토이인성인기명작동화옛날옛적에어리이야기애니메이션중국어버전,RMCzWSdF6ac,https://yt3.googleusercontent.com/rEqqVesoUJP5...
43,UCPvt1dbhi23-FTpGYZrmpLw,공포 흉가 귀신 무당 노래 커버 폐가 남캠 여캠 베스트 ghost 영안 부산희야 철...,HnAyM-iFjtU,https://yt3.googleusercontent.com/5i0HGrAuJLOd...
44,UCUEAfMdSYiXDfRVxdfqAQrg,교육 학교 교실 놀이 학급 선생님 체육 교실놀이 교실체육 운동장놀이 운동장체육 강당...,zfwCzOygVFI,https://yt3.googleusercontent.com/DqLPNQzOHumX...
45,UC8RUkja-IDFu10i5Rq3LX0A,#아레나 #아레나코리아 #수영복 #아레나수영복 #수영복추천 #실내수영복 #비치레저,TeGat1BT8XM,https://yt3.googleusercontent.com/VlaphQDJRBHz...
46,UCnss3Bsz1g9XpJBNM62vlWA,디아블로 이모탈 디아블로2 디아블로3 디아블로4 액션롤플레잉게임 모바일게임 바바리안...,v_49x4HKIv8,https://yt3.googleusercontent.com/LpWdUse-Khce...
47,UCA7WtDf9bYuRW1BowR00e6g,게임 롤 리그오브레전드 LOL 쓰레쉬 블리츠크랭크 서폿 서포터,tnXYpw9pgWA,https://yt3.googleusercontent.com/vcVdTk2G9SEQ...
48,UCzDLR2GTRqNsIFSnLacmdKg,조응천 국회 남양주 국회의원 법제사법위원회 chopros TV 티비 더불어민주당 의...,None,https://yt3.googleusercontent.com/8h5V2mfcm8lG...

### 4-6. status

In [155]:
rows = []
for item in response['items']:
    s = item.get('status', {})
    rows.append({
        'channel_id':          item['id'],
        'privacy_status':      s.get('privacyStatus'),       # ○ public / private / unlisted
        'is_linked':           s.get('isLinked'),             # ○ Google 계정 연결 여부
        'long_uploads_status': s.get('longUploadsStatus'),   # ○ 15분 초과 업로드 가능 여부
        'made_for_kids':       s.get('madeForKids'),         # ○ 어린이용 채널 여부
    })

pd.DataFrame(rows)

,channel_id,privacy_status,is_linked,long_uploads_status,made_for_kids
0,UCfxGrUvr10MjaCVKE_HVGgw,public,True,longUploadsUnspecified,None
1,UCFHt4Drs8lmyd-aUsBqM5uQ,public,True,longUploadsUnspecified,None
2,UCG6jmnh5Qw2SZYIPsN2Azfw,public,True,longUploadsUnspecified,None
3,UC5p-SkOSlkZRiF6CRdIFJvw,public,True,longUploadsUnspecified,None
4,UC76R9DL1NjD7aLr_C3eueLA,public,True,longUploadsUnspecified,False
5,UCktQ-dRsgT6IYjKXqw7fTCQ,public,True,longUploadsUnspecified,False
6,UCz0mNYCcfvetgrS7h0H-WcQ,public,True,longUploadsUnspecified,None
7,UC-Id9P16Dnutun3wual1fcA,public,True,longUploadsUnspecified,True
8,UC20IAd2RgxMkSNAbiRVMdGQ,public,True,longUploadsUnspecified,False
9,UCGqrzELBIpH6kfgJsNcZgeQ,public,True,longUploadsUnspecified,False
10,UCHHmDl_k97jLSOYbKEflr5Q,public,True,longUploadsUnspecified,None
11,UCopSrNAWJnzm4ETOS4mXHnw,public,True,longUploadsUnspecified,False
12,UCx7ThnRlyrSSiNCLIZI0aqQ,public,True,longUploadsUnspecified,False
13,UCW53Pedlt62rx5zuTRZKUow,public,True,longUploadsUnspecified,False
14,UCa98sUKOO-0ZoqmnOlY1i2g,public,True,longUploadsUnspecified,False
15,UC0CN1kbW3RuSz60bE9ELHcw,public,True,longUploadsUnspecified,False
16,UC6oN6MLpxu2CbCCIsQET0iA,public,True,longUploadsUnspecified,None
17,UCYhXoMjqKjfbh_bg57CyTIQ,public,True,longUploadsUnspecified,True
18,UC66duPrHKb_TJge0IL8x_9g,public,True,longUploadsUnspecified,False
19,UCVkE4YghTzGO61KHRsmffag,public,True,longUploadsUnspecified,True
20,UCCtKt-yPCrhLd6nlgJQc4RQ,public,True,longUploadsUnspecified,None
21,UCIb_O9AwrmaCXquQJ0TIVdw,public,True,longUploadsUnspecified,None
22,UC-MAo6JvPw49wWJzTePGF5Q,public,True,longUploadsUnspecified,None
23,UCHzxtmQhWwhFajAhtgfumKg,public,True,longUploadsUnspecified,None
24,UCPQ887rCYjOSSxN6nXqAojg,public,True,longUploadsUnspecified,False
25,UCfVqqxdFMvN4f0-isg0_bbw,public,True,longUploadsUnspecified,False
26,UCgXzwGNQLKQ4LA4XmWYWuvw,public,True,longUploadsUnspecified,None
27,UCkmNa3uEggjZis2eYbaXXnA,public,True,longUploadsUnspecified,False
28,UCstHL8TQy5hjCSIxK370aow,public,True,longUploadsUnspecified,False
29,UChC6A-YfVfQ9jbqG5zb4gjw,public,True,longUploadsUnspecified,None
30,UC7SSJS5huELNkaI6XhoNpNw,public,True,longUploadsUnspecified,None
31,UCc8RR9yJEKVvP31OWBqhIjg,public,True,longUploadsUnspecified,False
32,UC3QWksal35X_nSXE8jC59_A,public,True,longUploadsUnspecified,False
33,UC9mpnu1x96y7utLpnYyU6kw,public,True,longUploadsUnspecified,None
34,UCGGhcGI2JzKmtpSUkqSm7HQ,public,True,longUploadsUnspecified,False
35,UCsnakEva6XIr8rf0P8R_vBQ,public,True,longUploadsUnspecified,False
36,UCKcwMdtuEELC4hn_fUlfVrA,public,True,longUploadsUnspecified,False
37,UC9hWQRe4QrUivXN3VO2iuMA,public,True,longUploadsUnspecified,False
38,UCH7XQue96n6LH2EBwcp5_Xw,public,True,longUploadsUnspecified,False
39,UC7ddGHlf5sUc3w3yeMRqTLA,public,True,longUploadsUnspecified,False
40,UCS_GfKlHjjFwgIqGyZOwbtA,public,True,longUploadsUnspecified,None
41,UCJ2jmRmeLWFtVQQPsut9v8w,public,True,longUploadsUnspecified,None
42,UCS7_uGiAocfn0JGrJliGVrA,public,True,longUploadsUnspecified,None
43,UCPvt1dbhi23-FTpGYZrmpLw,public,True,longUploadsUnspecified,False
44,UCUEAfMdSYiXDfRVxdfqAQrg,public,True,longUploadsUnspecified,None
45,UC8RUkja-IDFu10i5Rq3LX0A,public,True,longUploadsUnspecified,None
46,UCnss3Bsz1g9XpJBNM62vlWA,public,True,longUploadsUnspecified,False
47,UCA7WtDf9bYuRW1BowR00e6g,public,True,longUploadsUnspecified,None
48,UCzDLR2GTRqNsIFSnLacmdKg,public,True,longUploadsUnspecified,False

## 5. 이탈 예측에 사용할 필드 정리

| 필드 | Part | 용도 |
|------|------|------|
| `channel_id` | — | 키 |
| `published_at` | snippet | ⭐ 채널 나이 계산 |
| `country` | snippet | ○ 국가 피처 |
| `uploads_playlist` | contentDetails | ⭐ 영상 수집 (01b 노트북) |
| `subscriber_count` | statistics | ⭐ 규모 피처 |
| `view_count` | statistics | ⭐ 총 조회수 |
| `video_count` | statistics | ⭐ 총 영상 수 |

## 6. 결과 저장

In [156]:
# 실제로 성공한 범위
actual_end_idx = last_completed_idx
total = len(df_all)

if actual_end_idx < START_IDX or not response['items']:
    print('⚠ 한 건도 수집하지 못함 — CSV 저장을 생략합니다.')
    print(f'▶ 다음 실행 시 START_IDX = {START_IDX} 로 다시 시도하세요.')
else:
    # 원시 API 응답 전체 저장
    out_raw = JSON_DIR / f'channels_raw_{START_IDX}_{actual_end_idx}.json'
    with open(out_raw, 'w', encoding='utf-8') as f:
        json.dump(response['items'], f, indent=2, ensure_ascii=False)
    print(f'원시 저장: {out_raw}')

    # MUST 필드 추출
    must_rows = []
    for item in response['items']:
        s  = item.get('snippet', {})
        cd = item.get('contentDetails', {}).get('relatedPlaylists', {})
        st = item.get('statistics', {})
        must_rows.append({
            'channel_id':       item['id'],
            'title':            s.get('title'),
            'published_at':     s.get('publishedAt'),
            'country':          s.get('country'),
            'uploads_playlist': cd.get('uploads'),
            'subscriber_count': st.get('subscriberCount'),
            'view_count':       st.get('viewCount'),
            'video_count':      st.get('videoCount'),
        })

    df_must = pd.DataFrame(must_rows)
    out_csv = CSV_DIR / f'channels_must_{START_IDX}_{actual_end_idx}.csv'
    df_must.to_csv(out_csv, index=False, encoding='utf-8-sig')
    print(f'MUST 필드 저장: {out_csv} ({len(df_must)}개 행)')

    # 다음 실행 안내
    if actual_end_idx < END_IDX:
        print(f'\n⚠ API 에러로 일부만 처리됨 — 요청 {START_IDX}~{END_IDX} / 성공 {START_IDX}~{actual_end_idx}')
        print(f'▶ 다음 실행 시 START_IDX = {actual_end_idx + 1} 부터 다시 시작하세요.')
    else:
        print(f'\n✓ 요청 범위 {START_IDX}~{END_IDX} 전체 처리 완료')
        if actual_end_idx + 1 < total:
            remaining = total - actual_end_idx - 1
            print(f'▶ 다음 실행 시 START_IDX = {actual_end_idx + 1} (전체 {total}개 중 {remaining}개 남음)')
        else:
            print(f'▶ youtube_channels_cleaned.csv 전체 처리 완료 (총 {total}개)')

    df_must.head()

원시 저장: ../../data/raw/channels/json/channels_raw_800_849.json
MUST 필드 저장: ../../data/raw/channels/csv/channels_must_800_849.csv (49개 행)

✓ 요청 범위 800~849 전체 처리 완료
▶ 다음 실행 시 START_IDX = 850 (전체 8192개 중 7342개 남음)