# 전체 파일 통합을 위한 노트북

## 0. 라이브러리 & 설정

In [2]:
import pandas as pd
import glob
import os

# ── 파일이 있는 폴더 경로 
DATA_DIR1 = "../../data/raw/channels/csv"

print("DATA_DIR :", os.path.abspath(DATA_DIR1))

DATA_DIR : /Users/sj.kang/Desktop/project2/SKN30-2nd-1Team/data/raw/channels/csv

## 1. channels 파일 전체 통합

`channels_must_*.csv` 패턴으로 파일을 자동 탐색해서 하나로 합칩니다.

In [8]:
# 파일 목록 탐색
ch_files = sorted(glob.glob(os.path.join(DATA_DIR1, "channels_must_*.csv")))

print(f"발견된 channels 파일: {len(ch_files)}개")
for f in ch_files:
    print(f"  {os.path.basename(f)}")

발견된 channels 파일: 164개
  channels_must_0_49.csv
  channels_must_1000_1049.csv
  channels_must_100_149.csv
  channels_must_1050_1099.csv
  channels_must_1100_1149.csv
  channels_must_1150_1199.csv
  channels_must_1200_1249.csv
  channels_must_1250_1299.csv
  channels_must_1300_1349.csv
  channels_must_1350_1399.csv
  channels_must_1400_1449.csv
  channels_must_1450_1499.csv
  channels_must_1500_1549.csv
  channels_must_150_199.csv
  channels_must_1550_1599.csv
  channels_must_1600_1649.csv
  channels_must_1650_1699.csv
  channels_must_1700_1749.csv
  channels_must_1750_1799.csv
  channels_must_1800_1849.csv
  channels_must_1850_1899.csv
  channels_must_1900_1949.csv
  channels_must_1950_1999.csv
  channels_must_2000_2049.csv
  channels_must_200_249.csv
  channels_must_2050_2099.csv
  channels_must_2100_2149.csv
  channels_must_2150_2199.csv
  channels_must_2200_2249.csv
  channels_must_2250_2299.csv
  channels_must_2300_2349.csv
  channels_must_2350_2399.csv
  channels_must_2400_2449.csv
  channels_must_2450_2499.csv
  channels_must_2500_2549.csv
  channels_must_250_299.csv
  channels_must_2550_2599.csv
  channels_must_2600_2649.csv
  channels_must_2650_2699.csv
  channels_must_2700_2749.csv
  channels_must_2750_2799.csv
  channels_must_2800_2849.csv
  channels_must_2850_2899.csv
  channels_must_2900_2949.csv
  channels_must_2950_2999.csv
  channels_must_3000_3049.csv
  channels_must_300_349.csv
  channels_must_3050_3099.csv
  channels_must_3100_3149.csv
  channels_must_3150_3199.csv
  channels_must_3200_3249.csv
  channels_must_3250_3299.csv
  channels_must_3300_3349.csv
  channels_must_3350_3399.csv
  channels_must_3400_3449.csv
  channels_must_3450_3499.csv
  channels_must_3500_3549.csv
  channels_must_350_399.csv
  channels_must_3550_3599.csv
  channels_must_3600_3649.csv
  channels_must_3650_3699.csv
  channels_must_3700_3749.csv
  channels_must_3750_3799.csv
  channels_must_3800_3849.csv
  channels_must_3850_3899.csv
  channels_must_3900_3949.csv
  channels_must_3950_3999.csv
  channels_must_4000_4049.csv
  channels_must_400_449.csv
  channels_must_4050_4099.csv
  channels_must_4100_4149.csv
  channels_must_4150_4199.csv
  channels_must_4200_4249.csv
  channels_must_4250_4299.csv
  channels_must_4300_4349.csv
  channels_must_4350_4399.csv
  channels_must_4400_4449.csv
  channels_must_4450_4499.csv
  channels_must_4500_4549.csv
  channels_must_450_499.csv
  channels_must_4550_4599.csv
  channels_must_4600_4649.csv
  channels_must_4650_4699.csv
  channels_must_4700_4749.csv
  channels_must_4750_4799.csv
  channels_must_4800_4849.csv
  channels_must_4850_4899.csv
  channels_must_4900_4949.csv
  channels_must_4950_4999.csv
  channels_must_5000_5049.csv
  channels_must_500_549.csv
  channels_must_5050_5099.csv
  channels_must_50_99.csv
  channels_must_5100_5149.csv
  channels_must_5150_5199.csv
  channels_must_5200_5249.csv
  channels_must_5250_5299.csv
  channels_must_5300_5349.csv
  channels_must_5350_5399.csv
  channels_must_5400_5449.csv
  channels_must_5450_5499.csv
  channels_must_5500_5549.csv
  channels_must_550_599.csv
  channels_must_5550_5599.csv
  channels_must_5600_5649.csv
  channels_must_5650_5699.csv
  channels_must_5700_5749.csv
  channels_must_5750_5799.csv
  channels_must_5800_5849.csv
  channels_must_5850_5899.csv
  channels_must_5900_5949.csv
  channels_must_5950_5999.csv
  channels_must_6000_6049.csv
  channels_must_600_649.csv
  channels_must_6050_6099.csv
  channels_must_6100_6149.csv
  channels_must_6150_6199.csv
  channels_must_6200_6249.csv
  channels_must_6250_6299.csv
  channels_must_6300_6349.csv
  channels_must_6350_6399.csv
  channels_must_6400_6449.csv
  channels_must_6450_6499.csv
  channels_must_6500_6549.csv
  channels_must_650_699.csv
  channels_must_6550_6599.csv
  channels_must_6600_6649.csv
  channels_must_6650_6699.csv
  channels_must_6700_6749.csv
  channels_must_6750_6799.csv
  channels_must_6800_6849.csv
  channels_must_6850_6899.csv
  channels_must_6900_6949.csv
  channels_must_6950_6999.csv
  channels_must_7000_7049.csv
  channels_must_700_749.csv
  channels_must_7050_7099.csv
  channels_must_7100_7149.csv
  channels_must_7150_7199.csv
  channels_must_7200_7249.csv
  channels_must_7250_7299.csv
  channels_must_7300_7349.csv
  channels_must_7350_7399.csv
  channels_must_7400_7449.csv
  channels_must_7450_7499.csv
  channels_must_7500_7549.csv
  channels_must_750_799.csv
  channels_must_7550_7599.csv
  channels_must_7600_7649.csv
  channels_must_7650_7699.csv
  channels_must_7700_7749.csv
  channels_must_7750_7799.csv
  channels_must_7800_7849.csv
  channels_must_7850_7899.csv
  channels_must_7900_7949.csv
  channels_must_7950_7999.csv
  channels_must_8000_8049.csv
  channels_must_800_849.csv
  channels_must_8050_8099.csv
  channels_must_8100_8149.csv
  channels_must_8150_8191.csv
  channels_must_850_899.csv
  channels_must_900_949.csv
  channels_must_950_999.csv

In [9]:
# 파일별로 읽어서 리스트에 쌓기
ch_list = []
for f in ch_files:
    tmp = pd.read_csv(f)
    tmp["source_file"] = os.path.basename(f)   # 어느 파일에서 왔는지 추적용
    ch_list.append(tmp)
    print(f"  {os.path.basename(f):45s} {len(tmp):>4}행")

print()
all_channels = pd.concat(ch_list, ignore_index=True)
print(f"통합 후 shape : {all_channels.shape}")

  channels_must_0_49.csv                          50행
  channels_must_1000_1049.csv                     50행
  channels_must_100_149.csv                       47행
  channels_must_1050_1099.csv                     49행
  channels_must_1100_1149.csv                     50행
  channels_must_1150_1199.csv                     50행
  channels_must_1200_1249.csv                     50행
  channels_must_1250_1299.csv                     50행
  channels_must_1300_1349.csv                     50행
  channels_must_1350_1399.csv                     48행
  channels_must_1400_1449.csv                     46행
  channels_must_1450_1499.csv                     50행
  channels_must_1500_1549.csv                     50행
  channels_must_150_199.csv                       49행
  channels_must_1550_1599.csv                     48행
  channels_must_1600_1649.csv                     49행
  channels_must_1650_1699.csv                     49행
  channels_must_1700_1749.csv                     48행
  channels_must_1750_1799.csv                     50행
  channels_must_1800_1849.csv                     50행
  channels_must_1850_1899.csv                     49행
  channels_must_1900_1949.csv                     50행
  channels_must_1950_1999.csv                     50행
  channels_must_2000_2049.csv                     50행
  channels_must_200_249.csv                       50행
  channels_must_2050_2099.csv                     50행
  channels_must_2100_2149.csv                     48행
  channels_must_2150_2199.csv                     50행
  channels_must_2200_2249.csv                     50행
  channels_must_2250_2299.csv                     49행
  channels_must_2300_2349.csv                     50행
  channels_must_2350_2399.csv                     50행
  channels_must_2400_2449.csv                     48행
  channels_must_2450_2499.csv                     49행
  channels_must_2500_2549.csv                     49행
  channels_must_250_299.csv                       49행
  channels_must_2550_2599.csv                     48행
  channels_must_2600_2649.csv                     50행
  channels_must_2650_2699.csv                     50행
  channels_must_2700_2749.csv                     50행
  channels_must_2750_2799.csv                     50행
  channels_must_2800_2849.csv                     50행
  channels_must_2850_2899.csv                     48행
  channels_must_2900_2949.csv                     49행
  channels_must_2950_2999.csv                     50행
  channels_must_3000_3049.csv                     49행
  channels_must_300_349.csv                       50행
  channels_must_3050_3099.csv                     50행
  channels_must_3100_3149.csv                     50행
  channels_must_3150_3199.csv                     50행
  channels_must_3200_3249.csv                     49행
  channels_must_3250_3299.csv                     50행
  channels_must_3300_3349.csv                     49행
  channels_must_3350_3399.csv                     49행
  channels_must_3400_3449.csv                     50행
  channels_must_3450_3499.csv                     48행
  channels_must_3500_3549.csv                     50행
  channels_must_350_399.csv                       49행
  channels_must_3550_3599.csv                     50행
  channels_must_3600_3649.csv                     49행
  channels_must_3650_3699.csv                     49행
  channels_must_3700_3749.csv                     48행
  channels_must_3750_3799.csv                     49행
  channels_must_3800_3849.csv                     49행
  channels_must_3850_3899.csv                     49행
  channels_must_3900_3949.csv                     50행
  channels_must_3950_3999.csv                     50행
  channels_must_4000_4049.csv                     50행
  channels_must_400_449.csv                       49행
  channels_must_4050_4099.csv                     50행
  channels_must_4100_4149.csv                     50행
  channels_must_4150_4199.csv                     50행
  channels_must_4200_4249.csv                     49행
  channels_must_4250_4299.csv                     50행
  channels_must_4300_4349.csv                     50행
  channels_must_4350_4399.csv                     50행
  channels_must_4400_4449.csv                     48행
  channels_must_4450_4499.csv                     50행
  channels_must_4500_4549.csv                     50행
  channels_must_450_499.csv                       45행
  channels_must_4550_4599.csv                     49행
  channels_must_4600_4649.csv                     48행
  channels_must_4650_4699.csv                     50행
  channels_must_4700_4749.csv                     47행
  channels_must_4750_4799.csv                     50행
  channels_must_4800_4849.csv                     50행
  channels_must_4850_4899.csv                     50행
  channels_must_4900_4949.csv                     50행
  channels_must_4950_4999.csv                     50행
  channels_must_5000_5049.csv                     50행
  channels_must_500_549.csv                       48행
  channels_must_5050_5099.csv                     50행
  channels_must_50_99.csv                         50행
  channels_must_5100_5149.csv                     50행
  channels_must_5150_5199.csv                     50행
  channels_must_5200_5249.csv                     50행
  channels_must_5250_5299.csv                     50행
  channels_must_5300_5349.csv                     50행
  channels_must_5350_5399.csv                     50행
  channels_must_5400_5449.csv                     49행
  channels_must_5450_5499.csv                     50행
  channels_must_5500_5549.csv                     49행
  channels_must_550_599.csv                       49행
  channels_must_5550_5599.csv                     50행
  channels_must_5600_5649.csv                     50행
  channels_must_5650_5699.csv                     50행
  channels_must_5700_5749.csv                     49행
  channels_must_5750_5799.csv                     50행
  channels_must_5800_5849.csv                     49행
  channels_must_5850_5899.csv                     50행
  channels_must_5900_5949.csv                     50행
  channels_must_5950_5999.csv                     50행
  channels_must_6000_6049.csv                     50행
  channels_must_600_649.csv                       49행
  channels_must_6050_6099.csv                     50행
  channels_must_6100_6149.csv                     50행
  channels_must_6150_6199.csv                     50행
  channels_must_6200_6249.csv                     48행
  channels_must_6250_6299.csv                     50행
  channels_must_6300_6349.csv                     49행
  channels_must_6350_6399.csv                     50행
  channels_must_6400_6449.csv                     50행
  channels_must_6450_6499.csv                     50행
  channels_must_6500_6549.csv                     50행
  channels_must_650_699.csv                       50행
  channels_must_6550_6599.csv                     50행
  channels_must_6600_6649.csv                     50행
  channels_must_6650_6699.csv                     50행
  channels_must_6700_6749.csv                     50행
  channels_must_6750_6799.csv                     50행
  channels_must_6800_6849.csv                     49행
  channels_must_6850_6899.csv                     49행
  channels_must_6900_6949.csv                     49행
  channels_must_6950_6999.csv                     50행
  channels_must_7000_7049.csv                     50행
  channels_must_700_749.csv                       50행
  channels_must_7050_7099.csv                     50행
  channels_must_7100_7149.csv                     49행
  channels_must_7150_7199.csv                     50행
  channels_must_7200_7249.csv                     50행
  channels_must_7250_7299.csv                     50행
  channels_must_7300_7349.csv                     50행
  channels_must_7350_7399.csv                     48행
  channels_must_7400_7449.csv                     50행
  channels_must_7450_7499.csv                     50행
  channels_must_7500_7549.csv                     50행
  channels_must_750_799.csv                       49행
  channels_must_7550_7599.csv                     50행
  channels_must_7600_7649.csv                     49행
  channels_must_7650_7699.csv                     50행
  channels_must_7700_7749.csv                     50행
  channels_must_7750_7799.csv                     50행
  channels_must_7800_7849.csv                     49행
  channels_must_7850_7899.csv                     50행
  channels_must_7900_7949.csv                     50행
  channels_must_7950_7999.csv                     50행
  channels_must_8000_8049.csv                     50행
  channels_must_800_849.csv                       49행
  channels_must_8050_8099.csv                     50행
  channels_must_8100_8149.csv                     50행
  channels_must_8150_8191.csv                     42행
  channels_must_850_899.csv                       50행
  channels_must_900_949.csv                       49행
  channels_must_950_999.csv                       48행

통합 후 shape : (8108, 9)

In [10]:
# 중복 channel_id 확인
dup = all_channels.duplicated(subset="channel_id")
print(f"중복 channel_id : {dup.sum()}개")

if dup.sum() > 0:
    print("중복 행 제거")
    all_channels = all_channels.drop_duplicates(subset="channel_id").reset_index(drop=True)
    print(f"제거 후 shape  : {all_channels.shape}")

중복 channel_id : 0개

In [11]:
# null 현황
print("=== null 현황 ===")
print(all_channels.isnull().sum())
print()
all_channels.head(3)

=== null 현황 ===
channel_id             0
title                  0
published_at           0
country             1043
uploads_playlist       0
subscriber_count       0
view_count             0
video_count            0
source_file            0
dtype: int64

,channel_id,title,published_at,country,uploads_playlist,subscriber_count,view_count,video_count,source_file
0,UC8EiJ1MgI0S0UAqmWaTcoBw,기준TV,2018-12-18T10:07:33Z,NaN,UU8EiJ1MgI0S0UAqmWaTcoBw,3,495,17,channels_must_0_49.csv
1,UCTdCqgNr9RFJWXK8qZgxL5g,James1004,2008-03-17T12:33:16Z,NaN,UUTdCqgNr9RFJWXK8qZgxL5g,14,6,2,channels_must_0_49.csv
2,UCMCcdMTgIzzdpa2iP8RtS8g,ted youngtae Noh,2011-11-11T01:21:17Z,KR,UUMCcdMTgIzzdpa2iP8RtS8g,11,280,4,channels_must_0_49.csv

In [12]:
# 저장
out_ch = os.path.join(DATA_DIR1, "all_channels.csv")
all_channels.to_csv(out_ch, index=False, encoding="utf-8-sig")
print(f"저장 완료 : {out_ch}")
print(f"shape     : {all_channels.shape}")

저장 완료 : ../../data/raw/channels/csv/all_channels.csv
shape     : (8108, 9)

## 2. videos 파일 전체 통합

`videos_*.csv` 패턴으로 파일을 탐색합니다.  
각 파일에 **컬럼 밀림 오염 행**(published_at에 날짜 대신 숫자가 들어간 행)이  
포함되어 있을 수 있으므로 파일마다 필터링합니다.

In [14]:
DATA_DIR2 = "../../data/raw/videos/csv"

In [15]:
vi_files = sorted(glob.glob(os.path.join(DATA_DIR2, "videos_*.csv")))

print(f"발견된 videos 파일: {len(vi_files)}개")
for f in vi_files:
    print(f"  {os.path.basename(f)}")

발견된 videos 파일: 164개
  videos_0000-0049.csv
  videos_0050-0099.csv
  videos_0100-0149.csv
  videos_0150-0199.csv
  videos_0200-0249.csv
  videos_0250-0299.csv
  videos_0300-0349.csv
  videos_0350-0399.csv
  videos_0400-0449.csv
  videos_0450-0499.csv
  videos_0500-0549.csv
  videos_0550-0599.csv
  videos_0600-0649.csv
  videos_0650-0699.csv
  videos_0700-0749.csv
  videos_0750-0799.csv
  videos_0800-0849.csv
  videos_0850-0899.csv
  videos_0900-0949.csv
  videos_0950-0999.csv
  videos_1000-1049.csv
  videos_1050-1099.csv
  videos_1100-1149.csv
  videos_1150-1199.csv
  videos_1200-1249.csv
  videos_1250-1299.csv
  videos_1300-1349.csv
  videos_1350-1399.csv
  videos_1400-1449.csv
  videos_1450-1499.csv
  videos_1500-1549.csv
  videos_1550-1599.csv
  videos_1600-1649.csv
  videos_1650-1699.csv
  videos_1700-1749.csv
  videos_1750-1799.csv
  videos_1800-1849.csv
  videos_1850-1899.csv
  videos_1900-1949.csv
  videos_1950-1999.csv
  videos_2000-2049.csv
  videos_2050-2099.csv
  videos_2100-2149.csv
  videos_2150-2199.csv
  videos_2200-2249.csv
  videos_2250-2299.csv
  videos_2300-2349.csv
  videos_2350-2399.csv
  videos_2400-2449.csv
  videos_2450-2499.csv
  videos_2500-2549.csv
  videos_2550-2599.csv
  videos_2600-2649.csv
  videos_2650-2699.csv
  videos_2700-2749.csv
  videos_2750-2799.csv
  videos_2800-2849.csv
  videos_2850-2899.csv
  videos_2900-2949.csv
  videos_2950-2999.csv
  videos_3000-3049.csv
  videos_3050-3099.csv
  videos_3100-3149.csv
  videos_3150-3199.csv
  videos_3200-3249.csv
  videos_3250-3299.csv
  videos_3300-3349.csv
  videos_3350-3399.csv
  videos_3400-3449.csv
  videos_3450-3499.csv
  videos_3500-3549.csv
  videos_3550-3599.csv
  videos_3600-3649.csv
  videos_3650-3699.csv
  videos_3700-3749.csv
  videos_3750-3799.csv
  videos_3800-3849.csv
  videos_3850-3899.csv
  videos_3900-3949.csv
  videos_3950-3999.csv
  videos_4000-4049.csv
  videos_4050-4099.csv
  videos_4100-4149.csv
  videos_4150-4199.csv
  videos_4200-4249.csv
  videos_4250-4299.csv
  videos_4300-4349.csv
  videos_4350-4399.csv
  videos_4400-4449.csv
  videos_4450-4499.csv
  videos_4500-4549.csv
  videos_4550-4599.csv
  videos_4600-4649.csv
  videos_4650-4699.csv
  videos_4700-4749.csv
  videos_4750-4799.csv
  videos_4800-4849.csv
  videos_4850-4899.csv
  videos_4900-4949.csv
  videos_4950-4999.csv
  videos_5000-5049.csv
  videos_5050-5099.csv
  videos_5100-5149.csv
  videos_5150-5199.csv
  videos_5200-5249.csv
  videos_5250-5299.csv
  videos_5300-5349.csv
  videos_5350-5399.csv
  videos_5400-5449.csv
  videos_5450-5499.csv
  videos_5500-5549.csv
  videos_5550-5599.csv
  videos_5600-5649.csv
  videos_5650-5699.csv
  videos_5700-5749.csv
  videos_5750-5799.csv
  videos_5800-5849.csv
  videos_5850-5899.csv
  videos_5900-5949.csv
  videos_5950-5999.csv
  videos_6000-6049.csv
  videos_6050-6099.csv
  videos_6100-6149.csv
  videos_6150-6199.csv
  videos_6200-6249.csv
  videos_6250-6299.csv
  videos_6300-6349.csv
  videos_6350-6399.csv
  videos_6400-6449.csv
  videos_6450-6499.csv
  videos_6500-6549.csv
  videos_6550-6599.csv
  videos_6600-6649.csv
  videos_6650-6699.csv
  videos_6700-6749.csv
  videos_6750-6799.csv
  videos_6800-6849.csv
  videos_6850-6899.csv
  videos_6900-6949.csv
  videos_6950-6999.csv
  videos_7000-7049.csv
  videos_7050-7099.csv
  videos_7100-7149.csv
  videos_7150-7199.csv
  videos_7200-7249.csv
  videos_7250-7299.csv
  videos_7300-7349.csv
  videos_7350-7399.csv
  videos_7400-7449.csv
  videos_7450-7499.csv
  videos_7500-7549.csv
  videos_7550-7599.csv
  videos_7600-7649.csv
  videos_7650-7699.csv
  videos_7700-7749.csv
  videos_7750-7799.csv
  videos_7800-7849.csv
  videos_7850-7899.csv
  videos_7900-7949.csv
  videos_7950-7999.csv
  videos_8000-8049.csv
  videos_8050-8099.csv
  videos_8100-8149.csv
  videos_8150-8191.csv

In [16]:
vi_list = []
total_bad = 0

for f in vi_files:
    tmp = pd.read_csv(f)

    # 오염 행 제거: published_at이 YYYY- 형식이 아닌 행
    bad_mask = ~tmp["published_at"].astype(str).str.match(r"\d{4}-", na=True)
    bad_count = bad_mask.sum()
    total_bad += bad_count

    tmp = tmp[~bad_mask].reset_index(drop=True)
    tmp["source_file"] = os.path.basename(f)
    vi_list.append(tmp)

    print(f"  {os.path.basename(f):40s} {len(tmp):>5}행  (오염 {bad_count}행 제거)")

print()
all_videos = pd.concat(vi_list, ignore_index=True)
print(f"통합 후 shape    : {all_videos.shape}")
print(f"총 오염 행 제거  : {total_bad}개")

  videos_0000-0049.csv                       654행  (오염 0행 제거)
  videos_0050-0099.csv                      1282행  (오염 0행 제거)
  videos_0100-0149.csv                      1384행  (오염 0행 제거)
  videos_0150-0199.csv                      1586행  (오염 0행 제거)
  videos_0200-0249.csv                      1783행  (오염 0행 제거)
  videos_0250-0299.csv                      2031행  (오염 0행 제거)
  videos_0300-0349.csv                      1979행  (오염 0행 제거)
  videos_0350-0399.csv                      1805행  (오염 0행 제거)
  videos_0400-0449.csv                      1868행  (오염 0행 제거)
  videos_0450-0499.csv                      1755행  (오염 0행 제거)
  videos_0500-0549.csv                      1890행  (오염 0행 제거)
  videos_0550-0599.csv                      2065행  (오염 0행 제거)
  videos_0600-0649.csv                      2084행  (오염 0행 제거)
  videos_0650-0699.csv                      2042행  (오염 0행 제거)
  videos_0700-0749.csv                      2137행  (오염 0행 제거)
  videos_0750-0799.csv                      2351행  (오염 0행 제거)
  videos_0800-0849.csv                      1954행  (오염 0행 제거)
  videos_0850-0899.csv                      2057행  (오염 0행 제거)
  videos_0900-0949.csv                      1986행  (오염 0행 제거)
  videos_0950-0999.csv                      2199행  (오염 0행 제거)
  videos_1000-1049.csv                      2025행  (오염 0행 제거)
  videos_1050-1099.csv                      2184행  (오염 0행 제거)
  videos_1100-1149.csv                      2123행  (오염 0행 제거)
  videos_1150-1199.csv                      2398행  (오염 0행 제거)
  videos_1200-1249.csv                      2183행  (오염 0행 제거)
  videos_1250-1299.csv                      2146행  (오염 0행 제거)
  videos_1300-1349.csv                      2287행  (오염 0행 제거)
  videos_1350-1399.csv                      2030행  (오염 0행 제거)
  videos_1400-1449.csv                      2200행  (오염 0행 제거)
  videos_1450-1499.csv                      2193행  (오염 0행 제거)
  videos_1500-1549.csv                      2080행  (오염 3행 제거)
  videos_1550-1599.csv                      2328행  (오염 0행 제거)
  videos_1600-1649.csv                      2152행  (오염 0행 제거)
  videos_1650-1699.csv                      2251행  (오염 0행 제거)
  videos_1700-1749.csv                      2180행  (오염 0행 제거)
  videos_1750-1799.csv                      2162행  (오염 0행 제거)
  videos_1800-1849.csv                      2176행  (오염 0행 제거)
  videos_1850-1899.csv                      2366행  (오염 0행 제거)
  videos_1900-1949.csv                      2321행  (오염 0행 제거)
  videos_1950-1999.csv                      2290행  (오염 0행 제거)
  videos_2000-2049.csv                      2221행  (오염 0행 제거)
  videos_2050-2099.csv                      2177행  (오염 0행 제거)
  videos_2100-2149.csv                      2134행  (오염 0행 제거)
  videos_2150-2199.csv                      2233행  (오염 0행 제거)
  videos_2200-2249.csv                      2312행  (오염 0행 제거)
  videos_2250-2299.csv                      2265행  (오염 0행 제거)
  videos_2300-2349.csv                      2306행  (오염 0행 제거)
  videos_2350-2399.csv                      2329행  (오염 0행 제거)
  videos_2400-2449.csv                      2232행  (오염 0행 제거)
  videos_2450-2499.csv                      2342행  (오염 0행 제거)
  videos_2500-2549.csv                      2302행  (오염 0행 제거)
  videos_2550-2599.csv                      2167행  (오염 0행 제거)
  videos_2600-2649.csv                      2329행  (오염 0행 제거)
  videos_2650-2699.csv                      2386행  (오염 0행 제거)
  videos_2700-2749.csv                      2224행  (오염 0행 제거)
  videos_2750-2799.csv                      2300행  (오염 0행 제거)
  videos_2800-2849.csv                      2355행  (오염 0행 제거)
  videos_2850-2899.csv                      2170행  (오염 0행 제거)
  videos_2900-2949.csv                      2251행  (오염 0행 제거)
  videos_2950-2999.csv                      2386행  (오염 0행 제거)
  videos_3000-3049.csv                      2413행  (오염 0행 제거)
  videos_3050-3099.csv                      2298행  (오염 0행 제거)
  videos_3100-3149.csv                      2285행  (오염 0행 제거)
  videos_3150-3199.csv                      2447행  (오염 0행 제거)
  videos_3200-3249.csv                      2357행  (오염 0행 제거)
  videos_3250-3299.csv                      2403행  (오염 0행 제거)
  videos_3300-3349.csv                      2411행  (오염 0행 제거)
  videos_3350-3399.csv                      2177행  (오염 0행 제거)
  videos_3400-3449.csv                      2307행  (오염 0행 제거)
  videos_3450-3499.csv                      2390행  (오염 0행 제거)
  videos_3500-3549.csv                      2387행  (오염 0행 제거)
  videos_3550-3599.csv                      2337행  (오염 0행 제거)
  videos_3600-3649.csv                      2388행  (오염 0행 제거)
  videos_3650-3699.csv                      2402행  (오염 0행 제거)
  videos_3700-3749.csv                      2249행  (오염 0행 제거)
  videos_3750-3799.csv                      2357행  (오염 0행 제거)
  videos_3800-3849.csv                      2341행  (오염 0행 제거)
  videos_3850-3899.csv                      2363행  (오염 0행 제거)
  videos_3900-3949.csv                      2238행  (오염 0행 제거)
  videos_3950-3999.csv                      2401행  (오염 0행 제거)
  videos_4000-4049.csv                      2481행  (오염 0행 제거)
  videos_4050-4099.csv                      2315행  (오염 0행 제거)
  videos_4100-4149.csv                      2427행  (오염 0행 제거)
  videos_4150-4199.csv                      2463행  (오염 0행 제거)
  videos_4200-4249.csv                      2256행  (오염 0행 제거)
  videos_4250-4299.csv                      2369행  (오염 0행 제거)
  videos_4300-4349.csv                      2361행  (오염 0행 제거)
  videos_4350-4399.csv                      2353행  (오염 0행 제거)
  videos_4400-4449.csv                      2436행  (오염 2행 제거)
  videos_4450-4499.csv                      2470행  (오염 0행 제거)
  videos_4500-4549.csv                      2330행  (오염 0행 제거)
  videos_4550-4599.csv                      2457행  (오염 0행 제거)
  videos_4600-4649.csv                      2367행  (오염 0행 제거)
  videos_4650-4699.csv                      2441행  (오염 0행 제거)
  videos_4700-4749.csv                      2242행  (오염 0행 제거)
  videos_4750-4799.csv                      2452행  (오염 0행 제거)
  videos_4800-4849.csv                      2421행  (오염 0행 제거)
  videos_4850-4899.csv                      2394행  (오염 0행 제거)
  videos_4900-4949.csv                      2433행  (오염 0행 제거)
  videos_4950-4999.csv                      2454행  (오염 0행 제거)
  videos_5000-5049.csv                      2347행  (오염 0행 제거)
  videos_5050-5099.csv                      2491행  (오염 0행 제거)
  videos_5100-5149.csv                      2500행  (오염 0행 제거)
  videos_5150-5199.csv                      2500행  (오염 0행 제거)
  videos_5200-5249.csv                      2459행  (오염 0행 제거)
  videos_5250-5299.csv                      2320행  (오염 0행 제거)
  videos_5300-5349.csv                      2403행  (오염 0행 제거)
  videos_5350-5399.csv                      2462행  (오염 0행 제거)
  videos_5400-5449.csv                      2469행  (오염 0행 제거)
  videos_5450-5499.csv                      2463행  (오염 0행 제거)
  videos_5500-5549.csv                      2351행  (오염 0행 제거)
  videos_5550-5599.csv                      2428행  (오염 0행 제거)
  videos_5600-5649.csv                      2488행  (오염 2행 제거)
  videos_5650-5699.csv                      2399행  (오염 0행 제거)
  videos_5700-5749.csv                      2403행  (오염 0행 제거)
  videos_5750-5799.csv                      2456행  (오염 0행 제거)
  videos_5800-5849.csv                      2402행  (오염 0행 제거)
  videos_5850-5899.csv                      2450행  (오염 0행 제거)
  videos_5900-5949.csv                      2500행  (오염 0행 제거)
  videos_5950-5999.csv                      2451행  (오염 0행 제거)
  videos_6000-6049.csv                      2384행  (오염 20행 제거)
  videos_6050-6099.csv                      2460행  (오염 0행 제거)
  videos_6100-6149.csv                      2464행  (오염 0행 제거)
  videos_6150-6199.csv                      2500행  (오염 0행 제거)
  videos_6200-6249.csv                      2400행  (오염 0행 제거)
  videos_6250-6299.csv                      2412행  (오염 0행 제거)
  videos_6300-6349.csv                      2500행  (오염 0행 제거)
  videos_6350-6399.csv                      2500행  (오염 0행 제거)
  videos_6400-6449.csv                      2452행  (오염 0행 제거)
  videos_6450-6499.csv                      2480행  (오염 0행 제거)
  videos_6500-6549.csv                      2421행  (오염 0행 제거)
  videos_6550-6599.csv                      2425행  (오염 0행 제거)
  videos_6600-6649.csv                      2442행  (오염 0행 제거)
  videos_6650-6699.csv                      2425행  (오염 0행 제거)
  videos_6700-6749.csv                      2479행  (오염 0행 제거)
  videos_6750-6799.csv                      2500행  (오염 0행 제거)
  videos_6800-6849.csv                      2376행  (오염 0행 제거)
  videos_6850-6899.csv                      2376행  (오염 0행 제거)
  videos_6900-6949.csv                      2405행  (오염 0행 제거)
  videos_6950-6999.csv                      2485행  (오염 0행 제거)
  videos_7000-7049.csv                      2455행  (오염 0행 제거)
  videos_7050-7099.csv                      2500행  (오염 0행 제거)
  videos_7100-7149.csv                      2402행  (오염 0행 제거)
  videos_7150-7199.csv                      2424행  (오염 0행 제거)
  videos_7200-7249.csv                      2500행  (오염 0행 제거)
  videos_7250-7299.csv                      2468행  (오염 0행 제거)
  videos_7300-7349.csv                      2500행  (오염 0행 제거)
  videos_7350-7399.csv                      2389행  (오염 0행 제거)
  videos_7400-7449.csv                      2448행  (오염 0행 제거)
  videos_7450-7499.csv                      2500행  (오염 0행 제거)
  videos_7500-7549.csv                      2481행  (오염 0행 제거)
  videos_7550-7599.csv                      2451행  (오염 0행 제거)
  videos_7600-7649.csv                      2484행  (오염 0행 제거)
  videos_7650-7699.csv                      2466행  (오염 0행 제거)
  videos_7700-7749.csv                      2500행  (오염 0행 제거)
  videos_7750-7799.csv                      2465행  (오염 0행 제거)
  videos_7800-7849.csv                      2422행  (오염 0행 제거)
  videos_7850-7899.csv                      2436행  (오염 0행 제거)
  videos_7900-7949.csv                      2500행  (오염 0행 제거)
  videos_7950-7999.csv                      2475행  (오염 0행 제거)
  videos_8000-8049.csv                      2464행  (오염 0행 제거)
  videos_8050-8099.csv                      2454행  (오염 0행 제거)
  videos_8100-8149.csv                      2454행  (오염 0행 제거)
  videos_8150-8191.csv                      2052행  (오염 0행 제거)

통합 후 shape    : (377579, 12)
총 오염 행 제거  : 27개

In [17]:
# 타입 변환
all_videos["published_at"] = pd.to_datetime(all_videos["published_at"], utc=True, errors="coerce")
all_videos["is_shorts"]    = all_videos["is_shorts"].astype(str).str.lower() == "true"

# published_at / channel_id null 제거
before = len(all_videos)
all_videos = all_videos.dropna(subset=["channel_id", "published_at"]).reset_index(drop=True)
print(f"null 제거 : {before - len(all_videos)}행 → {len(all_videos):,}행 남음")

null 제거 : 0행 → 377,579행 남음

In [18]:
# 중복 video_id 확인
dup_vi = all_videos.duplicated(subset="video_id")
print(f"중복 video_id : {dup_vi.sum()}개")

if dup_vi.sum() > 0:
    all_videos = all_videos.drop_duplicates(subset="video_id").reset_index(drop=True)
    print(f"제거 후 shape : {all_videos.shape}")

중복 video_id : 600개
제거 후 shape : (376979, 12)

In [19]:
# null 현황
print("=== null 현황 ===")
print(all_videos.isnull().sum())
print()
all_videos.head(3)

=== null 현황 ===
idx                  0
channel_id           0
channel_title        0
video_id             0
video_title          1
published_at         0
duration_sec      1343
is_shorts            0
view_count          12
like_count       13383
comment_count     9217
source_file          0
dtype: int64

,idx,channel_id,channel_title,video_id,video_title,published_at,duration_sec,is_shorts,view_count,like_count,comment_count,source_file
0,0,UCo3Yj54VtkEvQX9cLHKklzw,장정숙,eM25H_bOkJ4,171024 [장정숙 의원] 2017 국정감사_국립대 신입간호사 임금착취 문제 해결,2018-05-28 02:16:23+00:00,66.0,False,75.0,0.0,0.0,videos_0000-0049.csv
1,0,UCo3Yj54VtkEvQX9cLHKklzw,장정숙,KoovsJOVOEg,[국회의원 장정숙] 전반기 교육문화체육관광위원회 활동,2018-07-03 04:16:52+00:00,224.0,False,226.0,10.0,0.0,videos_0000-0049.csv
2,0,UCo3Yj54VtkEvQX9cLHKklzw,장정숙,VhXviHrA_yw,"191211 언제나 국민의편, 국회의원 장정숙",2019-12-11 05:58:53+00:00,86.0,False,192.0,2.0,0.0,videos_0000-0049.csv

In [20]:
# 저장
out_vi = os.path.join(DATA_DIR2, "all_videos.csv")
all_videos.to_csv(out_vi, index=False, encoding="utf-8-sig")
print(f"저장 완료 : {out_vi}")
print(f"shape     : {all_videos.shape}")

저장 완료 : ../../data/raw/videos/csv/all_videos.csv
shape     : (376979, 12)